#!/bin/bash
#
# Pekobot One-Line Installer
# Usage: curl -fsSL https://tools.coneko.ai/install.sh | bash
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
REPO="https://github.com/coneko/pekobot"
API_URL="https://tools.coneko.ai/api/v1"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/pekobot}"
DATA_DIR="${DATA_DIR:-$HOME/.local/share/pekobot}"

# Detect architecture and OS
detect_platform() {
    local arch=$(uname -m)
    local os=$(uname -s | tr '[:upper:]' '[:lower:]')
    
    case "$arch" in
        x86_64) arch="x86_64" ;;
        aarch64|arm64) arch="aarch64" ;;
        *) echo -e "${RED}Unsupported architecture: $arch${NC}"; exit 1 ;;
    esac
    
    case "$os" in
        linux) os="linux" ;;
        darwin) os="macos" ;;
        *) echo -e "${RED}Unsupported OS: $os${NC}"; exit 1 ;;
    esac
    
    echo "${os}_${arch}"
}

# Get latest release version
get_latest_version() {
    curl -fsSL "${API_URL}/releases/latest" 2>/dev/null | grep -o '"version":"[^"]*"' | cut -d'"' -f4 || echo "latest"
}

# Download and install binary
install_binary() {
    local platform=$1
    local version=$2
    local tmpdir=$(mktemp -d)
    local binary_name="pekobot-${platform}"
    local download_url="${API_URL}/releases/download/${version}/${binary_name}.tar.gz"
    
    echo -e "${BLUE}Downloading Pekobot ${version} for ${platform}...${NC}"
    
    if ! curl -fsSL "$download_url" -o "${tmpdir}/pekobot.tar.gz" 2>/dev/null; then
        # Fallback: try direct GitHub release
        download_url="${REPO}/releases/download/v${version}/${binary_name}.tar.gz"
        curl -fsSL "$download_url" -o "${tmpdir}/pekobot.tar.gz" || {
            echo -e "${RED}Failed to download binary${NC}"
            rm -rf "$tmpdir"
            exit 1
        }
    fi
    
    echo -e "${BLUE}Extracting...${NC}"
    tar -xzf "${tmpdir}/pekobot.tar.gz" -C "$tmpdir"
    
    # Install binary
    if [ -w "$INSTALL_DIR" ]; then
        mv "${tmpdir}/pekobot" "${INSTALL_DIR}/pekobot"
        chmod +x "${INSTALL_DIR}/pekobot"
    else
        echo -e "${YELLOW}Requesting sudo access to install to ${INSTALL_DIR}${NC}"
        sudo mv "${tmpdir}/pekobot" "${INSTALL_DIR}/pekobot"
        sudo chmod +x "${INSTALL_DIR}/pekobot"
    fi
    
    rm -rf "$tmpdir"
    echo -e "${GREEN}✓ Pekobot installed to ${INSTALL_DIR}/pekobot${NC}"
}

# Install systemd service (Linux only)
install_systemd_service() {
    if [ "$(uname -s)" != "Linux" ]; then
        return 0
    fi
    
    echo -e "${BLUE}Installing systemd service...${NC}"
    
    sudo tee /etc/systemd/system/pekobot.service > /dev/null <<EOF
[Unit]
Description=Pekobot Agent Runtime
After=network.target

[Service]
Type=simple
User=%I
ExecStart=${INSTALL_DIR}/pekobot daemon start
ExecStop=${INSTALL_DIR}/pekobot daemon stop
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    echo -e "${GREEN}✓ Systemd service installed${NC}"
    echo -e "${YELLOW}  Enable with: sudo systemctl enable pekobot@${USER}${NC}"
    echo -e "${YELLOW}  Start with: sudo systemctl start pekobot@${USER}${NC}"
}

# Create directories and config
setup_directories() {
    echo -e "${BLUE}Setting up directories...${NC}"
    
    mkdir -p "$CONFIG_DIR"
    mkdir -p "$DATA_DIR"
    mkdir -p "$DATA_DIR/tools"
    mkdir -p "$DATA_DIR/workspaces"
    
    # Create default config if it doesn't exist
    if [ ! -f "${CONFIG_DIR}/config.toml" ]; then
        cat > "${CONFIG_DIR}/config.toml" <<EOF
# Pekobot Configuration
# Generated by install.sh on $(date -I)

[agent]
default_provider = "openai"
default_model = "gpt-4o-mini"

[memory]
type = "sqlite"
path = "${DATA_DIR}/memory.db"

[tools]
registry = "pekohub"
registry_url = "https://tools.coneko.ai"
auto_install = true

[daemon]
enabled = true
poll_interval = 15

[logging]
level = "info"
EOF
        echo -e "${GREEN}✓ Default config created at ${CONFIG_DIR}/config.toml${NC}"
    fi
}

# Check dependencies
check_dependencies() {
    local deps=("curl" "tar")
    local missing=()
    
    for dep in "${deps[@]}"; do
        if ! command -v "$dep" &> /dev/null; then
            missing+=("$dep")
        fi
    done
    
    if [ ${#missing[@]} -ne 0 ]; then
        echo -e "${RED}Missing dependencies: ${missing[*]}${NC}"
        echo -e "${YELLOW}Please install them and run again${NC}"
        exit 1
    fi
}

# Print post-install instructions
print_post_install() {
    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  Pekobot installed successfully!${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "${BLUE}Quick Start:${NC}"
    echo "  1. Set your API key:"
    echo "     export OPENAI_API_KEY='your-key-here'"
    echo ""
    echo "  2. Create your first agent:"
    echo "     pekobot agent create my-agent --provider openai"
    echo ""
    echo "  3. Start the agent:"
    echo "     pekobot agent start my-agent"
    echo ""
    echo "  4. Or run in daemon mode:"
    echo "     pekobot daemon start"
    echo ""
    echo -e "${BLUE}Configuration:${NC}"
    echo "  Config: ${CONFIG_DIR}/config.toml"
    echo "  Data:   ${DATA_DIR}"
    echo ""
    echo -e "${BLUE}Documentation:${NC}"
    echo "  https://docs.coneko.ai/pekobot"
    echo ""
    echo -e "${YELLOW}Need help? Join our Discord: https://discord.gg/clawd${NC}"
}

# Main installation flow
main() {
    echo -e "${BLUE}═══════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  Pekobot Installer${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════${NC}"
    echo ""
    
    # Check if already installed
    if command -v pekobot &> /dev/null; then
        echo -e "${YELLOW}Pekobot is already installed${NC}"
        echo -e "Run '${INSTALL_DIR}/pekobot update' to update to the latest version"
        echo ""
        read -p "Reinstall anyway? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 0
        fi
    fi
    
    check_dependencies
    
    local platform=$(detect_platform)
    local version=$(get_latest_version)
    
    echo -e "Platform: ${GREEN}${platform}${NC}"
    echo -e "Version:  ${GREEN}${version}${NC}"
    echo -e "Install:  ${GREEN}${INSTALL_DIR}${NC}"
    echo ""
    
    install_binary "$platform" "$version"
    setup_directories
    install_systemd_service
    
    print_post_install
}

# Handle flags
while [[ $# -gt 0 ]]; do
    case $1 in
        --version)
            VERSION="$2"
            shift 2
            ;;
        --install-dir)
            INSTALL_DIR="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: install.sh [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --version VERSION    Install specific version"
            echo "  --install-dir DIR    Install to custom directory"
            echo "  --help, -h          Show this help"
            echo ""
            echo "Environment:"
            echo "  INSTALL_DIR         Installation directory (default: /usr/local/bin)"
            echo "  CONFIG_DIR          Config directory (default: ~/.config/pekobot)"
            echo "  DATA_DIR            Data directory (default: ~/.local/share/pekobot)"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

main