//! Plan storage schema (v1).
//!
//! The on-disk shape of a [`PlanRecord`]. One record per file at
//! `<plans_dir>/<plan_id>.jsonl`, written via [`crate::PlanStorage`] with
//! `FileLock`-coordinated atomic replacement.
//!
//! This file owns:
//!
//! - The serializable record type ([`PlanRecord`]) and its node ([`PlanNode`])
//!   and status ([`PlanNodeStatus`]) enums.
//! - The [`NodeId`] newtype used to key dependencies and identify nodes
//!   across the record.
//! - Helper queries ([`PlanRecord::has_unresolved_nodes`],
//!   [`PlanRecord::ready_nodes`], [`PlanRecord::current_focus_nodes`],
//!   [`PlanRecord::validate_dag`]) that the runtime can call without
//!   touching storage.
//!
//! It deliberately does NOT own: edge representation (encoded inline as
//! [`PlanNode::depends_on`]), per-node attempt history (use
//! `PlanNodeStatus::Failed` as the single source of truth in v1), or the
//! runtime-derived `current_focus` (computed by
//! [`PlanRecord::current_focus_nodes`]).
//!
//! All enums that may gain variants in future schema versions are marked
//! `#[non_exhaustive]` so v1 readers tolerate v2 writes.

use std::collections::HashSet;
use std::fmt;

use chrono::{DateTime, Utc};
use peko_subject::PrincipalId;
use serde::{Deserialize, Serialize};

use crate::error::{PlanError, Result};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Schema version of the on-disk record. Bumped when an incompatible change
/// is made; the `schema_version` field on [`PlanRecord`] carries the version
/// that wrote a given record. u32 to leave headroom for the workspace's
/// lifetime.
pub const PLAN_SCHEMA_VERSION: u32 = 1;

/// Length of the random suffix in generated ids (`plan_<suffix>`,
/// `node_<suffix>`). Eight base36 chars gives 36^8 ≈ 2.8T possibilities —
/// comfortable for in-process id generation.
pub const ID_SUFFIX_LEN: usize = 8;

/// Lowercase base36 alphabet `[0-9a-z]`. Matches the convention in
/// `DATA_MODEL.md` §1.4.
const BASE36: &[u8] = b"0123456789abcdefghijklmnopqrstuvwxyz";

/// Format a `u32` into exactly [`ID_SUFFIX_LEN`] lowercase base36 chars,
/// most-significant-digit first, with leading zeros.
fn base36_id(n: u32) -> String {
    let mut out = [b'0'; ID_SUFFIX_LEN];
    let mut v = n;
    for slot in out.iter_mut().rev() {
        *slot = BASE36[(v % 36) as usize];
        v /= 36;
    }
    String::from_utf8(out.to_vec()).expect("BASE36 is valid ASCII; cannot fail")
}

fn parse_id_suffix(s: &str, prefix: &str) -> Result<String> {
    let rest = s.strip_prefix(prefix).ok_or_else(|| {
        PlanError::InvalidNodeId(format!("missing {prefix} prefix: {s:?}"))
    })?;
    if rest.len() != ID_SUFFIX_LEN {
        return Err(PlanError::InvalidNodeId(format!(
            "expected {ID_SUFFIX_LEN} base36 chars after {prefix:?}, got {} in {s:?}",
            rest.len()
        )));
    }
    if !rest.bytes().all(|b| BASE36.contains(&b)) {
        return Err(PlanError::InvalidNodeId(format!(
            "non-base36 chars in suffix of {s:?}"
        )));
    }
    Ok(rest.to_string())
}

// ---------------------------------------------------------------------------
// PlanRecord
// ---------------------------------------------------------------------------

/// Top-level on-disk record. One per file at `<plans_dir>/<plan_id>.jsonl`.
///
/// Schema-relevant invariants:
///
/// - `nodes` is the single source of truth for nodes. `depends_on` on each
///   node is the single source of truth for edges (v1 collapses the
///   separate `DagEdge` representation).
/// - `closed: Some(...)` is terminal; subsequent `close` calls return
///   [`PlanError::AlreadyClosed`].
/// - Storage does NOT enforce acyclicity. Use
///   [`PlanRecord::validate_dag`] for callers who want strictness.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PlanRecord {
    /// `plan_<8 base36 chars>`. Generated by [`PlanRecord::new`].
    pub plan_id: String,
    /// Owning principal. The storage layer does not authorize reads; the
    /// caller is expected to use `get_for_principal` / `update` /
    /// `list_for_principal` to enforce scope.
    pub principal_id: PrincipalId,
    /// Schema version that wrote this record. Always
    /// [`PLAN_SCHEMA_VERSION`] for v1 writes.
    pub schema_version: u32,
    /// Immutable plan title set at creation time. The runtime can rename
    /// via a `replace_title` closure passed to `PlanStorage::update` —
    /// the schema does not require immutability, but the runtime does.
    pub title: String,
    /// Plan creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Last mutation timestamp; updated by every `PlanStorage::update` /
    /// `PlanStorage::close`.
    pub updated_at: DateTime<Utc>,
    /// Plan nodes in insertion order. The runtime orders them via
    /// dependency resolution; this vec preserves writer intent.
    pub nodes: Vec<PlanNode>,
    /// Terminal state. `None` while the plan is open.
    pub closed: Option<ClosedState>,
}

impl PlanRecord {
    /// Construct a fresh `PlanRecord` from caller-supplied inputs.
    ///
    /// Generation of `plan_id`, `schema_version`, and timestamps is the
    /// only work the constructor does — the storage layer (`create`)
    /// invokes this and then writes the result atomically.
    pub fn new(principal_id: PrincipalId, title: String, mut nodes: Vec<PlanNode>) -> Self {
        let now = Utc::now();
        // Stamp each newly-supplied node with creation timestamps so the
        // caller doesn't have to.
        for n in &mut nodes {
            n.created_at = now;
            n.updated_at = now;
        }
        Self {
            plan_id: format!("plan_{}", base36_id(rand_u32())),
            principal_id,
            schema_version: PLAN_SCHEMA_VERSION,
            title,
            created_at: now,
            updated_at: now,
            nodes,
            closed: None,
        }
    }

    /// True iff any node is not `Completed` and the plan isn't closed.
    /// This is the predicate the runtime checks before re-injecting a plan
    /// into a fresh session's context.
    pub fn has_unresolved_nodes(&self) -> bool {
        if self.closed.is_some() {
            return false;
        }
        self.nodes
            .iter()
            .any(|n| !matches!(n.status, PlanNodeStatus::Completed { .. }))
    }

    /// All `Pending` nodes whose `depends_on` set is entirely `Completed`.
    /// Used by the runtime to compute the "next actionable" surface.
    pub fn ready_nodes(&self) -> Vec<&PlanNode> {
        let completed: HashSet<&NodeId> = self
            .nodes
            .iter()
            .filter(|n| matches!(n.status, PlanNodeStatus::Completed { .. }))
            .map(|n| &n.node_id)
            .collect();

        self.nodes
            .iter()
            .filter(|n| matches!(n.status, PlanNodeStatus::Pending))
            .filter(|n| n.depends_on.iter().all(|dep| completed.contains(dep)))
            .collect()
    }

    /// All `InProgress` nodes. In v1, the schema permits multiple; the
    /// agent (not the storage layer) is responsible for single-track
    /// discipline. v2 may add a runtime-enforced single-focus invariant.
    pub fn current_focus_nodes(&self) -> Vec<&PlanNode> {
        self.nodes
            .iter()
            .filter(|n| matches!(n.status, PlanNodeStatus::InProgress))
            .collect()
    }

    /// DFS cycle check. Returns `Err(PlanError::InvalidNodeId)` if a
    /// `depends_on` references a node that doesn't exist; returns
    /// `Err(CorruptCycle)` if the graph has a cycle. Storage does NOT
    /// call this — it's available to the runtime for callers who want
    /// strictness on `create`.
    pub fn validate_dag(&self) -> Result<()> {
        let ids: HashSet<&NodeId> = self.nodes.iter().map(|n| &n.node_id).collect();

        // First pass: every depends_on target must exist.
        for n in &self.nodes {
            for dep in &n.depends_on {
                if !ids.contains(dep) {
                    return Err(PlanError::InvalidNodeId(format!(
                        "node {} depends on missing node {}",
                        n.node_id.as_str(),
                        dep.as_str()
                    )));
                }
            }
        }

        // Second pass: cycle check via DFS with white/grey/black coloring.
        // Implemented by *index* into `nodes` — values, not references —
        // because stacked references into a borrowed graph fragment fight
        // the borrow checker on multi-branch DFS. Indices are stable for
        // the duration of a single call.
        #[derive(Debug, Copy, Clone, Eq, PartialEq)]
        enum Color {
            White,
            Grey,
            Black,
        }
        let mut color: Vec<Color> = vec![Color::White; self.nodes.len()];

        // Build a forward adjacency by index: dep -> [things that depend on dep].
        // The dep-existence check above guarantees all `deps[j]` indices
        // are valid.
        let mut forward: Vec<Vec<usize>> = vec![Vec::new(); self.nodes.len()];
        let nodes_by_id: std::collections::HashMap<&NodeId, usize> = self
            .nodes
            .iter()
            .enumerate()
            .map(|(i, n)| (&n.node_id, i))
            .collect();
        for (i, n) in self.nodes.iter().enumerate() {
            for dep in &n.depends_on {
                let j = *nodes_by_id.get(dep).expect("dep existence checked above");
                forward[j].push(i);
            }
        }

        // Iterative DFS: each frame holds the remaining-neighbors list of
        // one frame-node. `frame_nodes[i]` parallels `stack[i]` and is
        // the canonical node id for that frame. Standard 3-color DFS.
        let mut stack: Vec<Vec<usize>> = Vec::new();
        let mut frame_nodes: Vec<usize> = Vec::new();

        for start in 0..self.nodes.len() {
            if color[start] != Color::White {
                continue;
            }
            color[start] = Color::Grey;
            stack.push(forward[start].clone());
            frame_nodes.push(start);

            while !stack.is_empty() {
                // Scoped borrow: `last_mut()` and `pop()` are on a single
                // expression so the mutable borrow ends before the match.
                let next_opt = stack.last_mut().unwrap().pop();
                match next_opt {
                    Some(next) => match color[next] {
                        Color::White => {
                            color[next] = Color::Grey;
                            stack.push(forward[next].clone());
                            frame_nodes.push(next);
                        }
                        Color::Grey => {
                            return Err(PlanError::InvalidNodeId(format!(
                                "plan has cycle through node {}",
                                self.nodes[next].node_id.as_str()
                            )));
                        }
                        Color::Black => {}
                    },
                    None => {
                        // Frame exhausted: mark Black and pop.
                        let done = frame_nodes.pop().unwrap();
                        color[done] = Color::Black;
                        stack.pop();
                    }
                }
            }
        }

        Ok(())
    }
}

// ---------------------------------------------------------------------------
// PlanNode
// ---------------------------------------------------------------------------

/// A single step inside a [`PlanRecord`].
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PlanNode {
    /// `node_<8 base36 chars>`.
    pub node_id: NodeId,
    /// Human title; max length is not enforced — caller can truncate if
    /// the runtime wants.
    pub step: String,
    /// Current state. Single source of truth for "where this node is".
    pub status: PlanNodeStatus,
    /// Dependencies on other nodes in the same plan. Order-independent.
    /// Empty means "no dependencies (can be `Pending` immediately)".
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub depends_on: Vec<NodeId>,
    /// Per-node output / artifacts / decided_by. `Some` once the node
    /// transitions away from `Pending`/`InProgress`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub evidence: Option<NodeEvidence>,
    /// Redundant fast-access mirror of `status::Blocked { reason }`.
    /// Kept so UI code can render blockers without pattern-matching the
    /// status. Schema-driven code should prefer `status`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub blocked_reason: Option<String>,
    /// Node creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Last mutation timestamp; updated whenever status / evidence /
    /// blocked_reason / depends_on change. Note: not updated for
    /// companion-record (`PlanRecord::updated_at`) mutations — that
    /// field is the *record's* last-touch.
    pub updated_at: DateTime<Utc>,
}

// ---------------------------------------------------------------------------
// PlanNodeStatus
// ---------------------------------------------------------------------------

/// Lifecycle state of a single [`PlanNode`].
///
/// `#[non_exhaustive]` so future schemas can add `Skipped`, `Cancelled`,
/// or refined `Failed` variants without breaking v1 readers.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[non_exhaustive]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum PlanNodeStatus {
    /// Not yet ready to act on (or its dependencies are not satisfied).
    Pending,
    /// Currently being worked on. Single-track is the convention; the
    /// storage layer permits multiple.
    InProgress,
    /// Done. `completed_at` is the wall-clock when the transition
    /// happened (mirrors the last `updated_at`, but carried in the
    /// variant payload for downstream serialization).
    Completed {
        completed_at: DateTime<Utc>,
    },
    /// Blocked on something outside the plan's control. Carries a
    /// human-readable reason and the timestamp of when the blocker was
    /// first recorded (vs. `last_attempt_at` for `Failed`).
    Blocked {
        reason: String,
        since: DateTime<Utc>,
    },
    /// Failed after attempts. Carry last-attempt timestamp and reason.
    /// v2 may add an inline `Vec<AttemptRecord>` if retry lineage becomes
    /// important; for now the runtime records retried failures by bumping
    /// this variant's `last_attempt_at` and appending a sibling evidence
    /// entry.
    Failed {
        reason: String,
        last_attempt_at: DateTime<Utc>,
    },
}

// ---------------------------------------------------------------------------
// NodeEvidence
// ---------------------------------------------------------------------------

/// Per-node recorded result. `Some` once the node transitions away from
/// `Pending`/`InProgress`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NodeEvidence {
    /// Short textual result. Long-form output should go to `artifacts`
    /// (paths) or to a referenced session record.
    pub output: String,
    /// Free-form list of artifact references — file paths, session ids,
    /// commit SHAs, URLs. Not validated by the storage layer.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub artifacts: Vec<String>,
    /// Who produced this evidence. Free-form in v1; v2 may type as
    /// `peko_subject::Subject`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decided_by: Option<String>,
}

// ---------------------------------------------------------------------------
// ClosedState
// ---------------------------------------------------------------------------

/// Terminal state of a [`PlanRecord`]. `#[non_exhaustive]` so v2 can
/// carry a `closed_by` without breaking v1 readers.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[non_exhaustive]
pub struct ClosedState {
    pub closed_at: DateTime<Utc>,
    pub reason: String,
}

impl ClosedState {
    /// Construct a [`ClosedState`] with `closed_at = now()`. The
    /// `#[non_exhaustive]` attribute blocks cross-crate struct
    /// expressions, so external callers (test fixtures, the
    /// `peko_plan` tool surface) need this constructor.
    #[must_use]
    pub fn new(reason: String) -> Self {
        Self {
            closed_at: Utc::now(),
            reason,
        }
    }
}

// ---------------------------------------------------------------------------
// NodeId
// ---------------------------------------------------------------------------

/// Typed identifier for a single node inside a plan.
///
/// `node_<8 base36 chars>` (DATA_MODEL.md §1.4). Inner is `pub(crate)` —
/// callers reach it via [`NodeId::as_str`].
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct NodeId(String);

impl NodeId {
    pub const PREFIX: &'static str = "node_";

    /// Generate a fresh, unique id. Uses [`rand_u32`] for the suffix;
    /// collisions are astronomically unlikely (36^8 / process = 0 in
    /// any realistic plan size).
    pub fn generate() -> Self {
        Self(format!("{}{}", Self::PREFIX, base36_id(rand_u32())))
    }

    /// Parse a string back into a `NodeId`, validating the prefix and
    /// the 8 base36 suffix.
    pub fn parse(s: &str) -> Result<Self> {
        parse_id_suffix(s, Self::PREFIX)?;
        Ok(Self(s.to_string()))
    }

    /// Borrow the inner string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for NodeId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl Serialize for NodeId {
    fn serialize<S: serde::Serializer>(&self, ser: S) -> std::result::Result<S::Ok, S::Error> {
        ser.serialize_str(&self.0)
    }
}

impl<'de> Deserialize<'de> for NodeId {
    fn deserialize<D: serde::Deserializer<'de>>(de: D) -> std::result::Result<Self, D::Error> {
        let s = String::deserialize(de)?;
        Self::parse(&s).map_err(serde::de::Error::custom)
    }
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

/// Cheap, per-process monotonic counter mixed with wall-clock nanos +
/// pid. Avoids pulling in `rand`; the entropy is more than enough for
/// `node_<8 base36>` ids and `plan_<8 base36>` ids within a single
/// process.
///
/// Two consecutive calls within the same nanosecond are distinguished
/// by the counter, so collisions within one process are not possible
/// (would require the counter to wrap, which never happens in u64).
/// The mixing is *not* a CSPRNG; for cryptographic ids callers should
/// supply their own entropy.
fn rand_u32() -> u32 {
    use std::sync::atomic::{AtomicU64, Ordering};
    static CTR: AtomicU64 = AtomicU64::new(0);

    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0);
    let pid = std::process::id() as u64;
    let ctr = CTR.fetch_add(1, Ordering::Relaxed);

    // Splitmix64-style mixing of three independent entropy sources.
    let mut z = now
        .wrapping_add(ctr.wrapping_mul(0x9E3779B97F4A7C15))
        .wrapping_add(pid.wrapping_mul(0xBF58476D1CE4E5B9));
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
    z ^= z >> 31;
    (z as u32) ^ ((z >> 32) as u32)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn ts(secs: i64) -> DateTime<Utc> {
        Utc.timestamp_opt(secs, 0).single().unwrap()
    }

    fn sample_node(label: &str) -> PlanNode {
        PlanNode {
            node_id: NodeId::generate(),
            step: label.to_string(),
            status: PlanNodeStatus::Pending,
            depends_on: vec![],
            evidence: None,
            blocked_reason: None,
            created_at: ts(1_700_000_000),
            updated_at: ts(1_700_000_000),
        }
    }

    fn sample_record() -> PlanRecord {
        let principal = PrincipalId::generate();
        PlanRecord::new(principal, "Migrate auth".to_string(), vec![sample_node("Wire SQLX")])
    }

    #[test]
    fn round_trip_full_record_serde() {
        let mut record = sample_record();
        // Populate every optional field so we round-trip with full shape.
        let n0 = &mut record.nodes[0];
        n0.status = PlanNodeStatus::InProgress;
        n0.evidence = Some(NodeEvidence {
            output: "scoped schema migrations".to_string(),
            artifacts: vec!["migrations/2026_07_31_init.sql".to_string()],
            decided_by: Some("subagent:explore-1".to_string()),
        });

        let json = serde_json::to_string(&record).expect("serialize");
        let decoded: PlanRecord = serde_json::from_str(&json).expect("deserialize");

        assert_eq!(decoded, record);
    }

    #[test]
    fn round_trip_empty_plan() {
        let principal = PrincipalId::generate();
        let record = PlanRecord::new(principal, "Empty".to_string(), vec![]);
        let json = serde_json::to_string(&record).expect("serialize");
        let decoded: PlanRecord = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(decoded, record);
        assert!(decoded.nodes.is_empty());
        assert!(decoded.closed.is_none());
    }

    #[test]
    fn has_unresolved_nodes_three_cases() {
        let mut record = sample_record();
        // Case 1: one Pending node → unresolved.
        assert!(record.has_unresolved_nodes());

        // Case 2: all Completed → not unresolved.
        for n in &mut record.nodes {
            n.status = PlanNodeStatus::Completed {
                completed_at: ts(1_700_000_500),
            };
        }
        assert!(!record.has_unresolved_nodes());

        // Case 3: closed → not unresolved regardless of node status.
        let mut closed = record.clone();
        closed.nodes[0].status = PlanNodeStatus::Pending; // counter the prior change
        closed.closed = Some(ClosedState {
            closed_at: ts(1_700_001_000),
            reason: "abandoned".to_string(),
        });
        assert!(!closed.has_unresolved_nodes());
    }

    #[test]
    fn ready_nodes_deps_satisfied_vs_not() {
        let mut record = sample_record();
        // Two nodes: A (no deps), B (depends on A). Both Pending → only
        // A is ready.
        let a_id = NodeId::generate();
        let b_id = NodeId::generate();
        record.nodes = vec![
            PlanNode {
                node_id: a_id.clone(),
                step: "A".to_string(),
                status: PlanNodeStatus::Pending,
                depends_on: vec![],
                evidence: None,
                blocked_reason: None,
                created_at: ts(1_700_000_000),
                updated_at: ts(1_700_000_000),
            },
            PlanNode {
                node_id: b_id.clone(),
                step: "B".to_string(),
                status: PlanNodeStatus::Pending,
                depends_on: vec![a_id.clone()],
                evidence: None,
                blocked_reason: None,
                created_at: ts(1_700_000_000),
                updated_at: ts(1_700_000_000),
            },
        ];

        let ready = record.ready_nodes();
        assert_eq!(ready.len(), 1);
        assert_eq!(ready[0].node_id, a_id);

        // Complete A → B becomes ready.
        record.nodes[0].status = PlanNodeStatus::Completed {
            completed_at: ts(1_700_000_500),
        };
        let ready = record.ready_nodes();
        assert_eq!(ready.len(), 1);
        assert_eq!(ready[0].node_id, b_id);
    }

    #[test]
    fn validate_dag_accepts_acyclic() {
        let mut record = sample_record();
        let a = NodeId::generate();
        let b = NodeId::generate();
        record.nodes = vec![
            PlanNode {
                node_id: a.clone(),
                step: "A".into(),
                status: PlanNodeStatus::Pending,
                depends_on: vec![],
                evidence: None,
                blocked_reason: None,
                created_at: ts(1_700_000_000),
                updated_at: ts(1_700_000_000),
            },
            PlanNode {
                node_id: b.clone(),
                step: "B".into(),
                status: PlanNodeStatus::Pending,
                depends_on: vec![a],
                evidence: None,
                blocked_reason: None,
                created_at: ts(1_700_000_000),
                updated_at: ts(1_700_000_000),
            },
        ];
        let result = record.validate_dag();
        assert!(result.is_ok(), "expected Ok, got {result:?}");
    }

    #[test]
    fn validate_dag_rejects_cycle() {
        let mut record = sample_record();
        let a = NodeId::generate();
        let b = NodeId::generate();
        record.nodes = vec![
            PlanNode {
                node_id: a.clone(),
                step: "A→B".into(),
                status: PlanNodeStatus::Pending,
                depends_on: vec![b.clone()],
                evidence: None,
                blocked_reason: None,
                created_at: ts(1_700_000_000),
                updated_at: ts(1_700_000_000),
            },
            PlanNode {
                node_id: b.clone(),
                step: "B→A".into(),
                status: PlanNodeStatus::Pending,
                depends_on: vec![a],
                evidence: None,
                blocked_reason: None,
                created_at: ts(1_700_000_000),
                updated_at: ts(1_700_000_000),
            },
        ];
        let err = record.validate_dag().expect_err("cycle must be rejected");
        assert!(matches!(err, PlanError::InvalidNodeId(_)));
    }

    #[test]
    fn validate_dag_rejects_missing_dep() {
        let mut record = sample_record();
        let orphan = NodeId::generate();
        let phantom = NodeId::generate();
        record.nodes = vec![PlanNode {
            node_id: orphan,
            step: "depends-on-phantom".into(),
            status: PlanNodeStatus::Pending,
            depends_on: vec![phantom],
            evidence: None,
            blocked_reason: None,
            created_at: ts(1_700_000_000),
            updated_at: ts(1_700_000_000),
        }];
        let err = record.validate_dag().expect_err("missing dep must be rejected");
        assert!(matches!(err, PlanError::InvalidNodeId(_)));
    }

    #[test]
    fn node_id_generate_distinct() {
        let mut seen = HashSet::new();
        for _ in 0..256 {
            let id = NodeId::generate();
            assert!(seen.insert(id.clone()), "duplicate generated NodeId: {id}");
            assert!(id.as_str().starts_with(NodeId::PREFIX));
        }
    }

    #[test]
    fn node_id_parse_round_trip() {
        let generated = NodeId::generate();
        let parsed = NodeId::parse(generated.as_str()).expect("parse generated");
        assert_eq!(parsed, generated);
    }

    #[test]
    fn node_id_parse_rejects_invalid() {
        // Wrong prefix
        assert!(NodeId::parse("plan_abc12345").is_err());
        // Too short
        assert!(NodeId::parse("node_abc").is_err());
        // Too long
        assert!(NodeId::parse("node_abcdefghi").is_err());
        // Non-base36 char (uppercase)
        assert!(NodeId::parse("node_ABCDEFGH").is_err());
    }

    #[test]
    fn current_focus_nodes_returns_in_progress() {
        let mut record = sample_record();
        record.nodes[0].status = PlanNodeStatus::InProgress;
        let focus = record.current_focus_nodes();
        assert_eq!(focus.len(), 1);
        assert_eq!(focus[0].node_id, record.nodes[0].node_id);
    }

    #[test]
    fn principal_id_display_and_serde_round_trip() {
        let p = PrincipalId::generate();
        let json = serde_json::to_string(&p).expect("ser");
        let back: PrincipalId = serde_json::from_str(&json).expect("de");
        assert_eq!(back, p);
        assert_eq!(back.to_string(), p.to_string());
    }
}
