//! Universal Tool Adapter for the Extension system
//!
//! This adapter integrates Universal Tools into the unified Extension
//! Architecture.
//!
//! # Universal Tool Format
//!
//! Universal tools are external executables with a `manifest.yaml`:
//! ```yaml
//! name: calculator
//! extension_type: universal-tool
//! description: Perform calculations
//! parameters:
//!   type: object
//!   properties:
//!     expression:
//!       type: string
//! ```
//!
//! # Registration
//!
//! Tools are registered via the unified registry (`ExtensionCore::register_tool()`).
//! Companion hooks (prompt, async, status, cancel) are auto-generated by the
//! registry; this adapter only supplies the execution handler.

use crate::extensions::framework::adapters::{ExtensionTypeAdapter, ManifestFormat};
use crate::extensions::framework::core::{
    ExtensionCore, HookBinding, HookContext, HookHandler, HookPoint, ToolMetadata, ToolSource,
};
use crate::extensions::framework::types::{ExtensionId, ExtensionManifest, HookResult};
use anyhow::{Context, Result};
use async_trait::async_trait;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tracing::{debug, info, trace, warn};

/// Universal tool extension type identifier
pub const UNIVERSAL_TOOL_EXTENSION_TYPE: &str = "universal-tool";

/// Default priority for universal tool hooks
pub const UNIVERSAL_TOOL_HOOK_PRIORITY: i32 = 75;

/// Universal tool adapter for Extension system
#[derive(Debug)]
pub struct UniversalToolAdapter;

impl UniversalToolAdapter {
    /// Create a new universal tool adapter
    #[must_use]
    pub fn new() -> Self {
        Self
    }

    /// Discover universal tools from a directory
    pub async fn discover_tools(&self, path: &Path) -> Vec<DiscoveredUniversalTool> {
        let mut tools = Vec::new();

        if !path.exists() {
            debug!("Tools directory does not exist: {:?}", path);
            return tools;
        }

        let mut entries = match tokio::fs::read_dir(path).await {
            Ok(entries) => entries,
            Err(e) => {
                warn!("Failed to read tools directory {:?}: {}", path, e);
                return tools;
            }
        };

        // Scan directory for tool subdirectories
        while let Some(entry) = entries.next_entry().await.ok().flatten() {
            let tool_path = entry.path();

            // Skip non-directories and hidden
            if !tool_path.is_dir() {
                continue;
            }

            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if name_str.starts_with('.') {
                continue;
            }

            // Look for manifest.yaml
            let manifest_path = tool_path.join("manifest.yaml");
            if !manifest_path.exists() {
                trace!("No manifest.yaml found in {}", tool_path.display());
                continue;
            }

            // Parse manifest to get tool info
            match self
                .parse_tool_manifest_with_discovery(&manifest_path)
                .await
            {
                Ok((manifest, tool_name)) => {
                    // Find executable
                    if let Some(executable) = self.find_executable(&tool_path, &tool_name).await {
                        tools.push(DiscoveredUniversalTool {
                            manifest,
                            executable,
                            manifest_path,
                        });
                    }
                }
                Err(e) => {
                    warn!("Failed to parse manifest {:?}: {}", manifest_path, e);
                }
            }
        }

        tools
    }

    /// Parse manifest and extract tool name for discovery
    async fn parse_tool_manifest_with_discovery(
        &self,
        manifest_path: &Path,
    ) -> Result<(ExtensionManifest, String)> {
        let content = tokio::fs::read_to_string(manifest_path)
            .await
            .with_context(|| format!("Failed to read manifest {manifest_path:?}"))?;

        let yaml: serde_yaml::Value = serde_yaml::from_str(&content)
            .with_context(|| format!("Failed to parse manifest {manifest_path:?}"))?;

        let tool_name = crate::extensions::framework::adapters::parsing::require_string_field(&yaml, "name")
            .or_else(|_| crate::extensions::framework::adapters::parsing::require_string_field(&yaml, "id"))?;
        let description =
            crate::extensions::framework::adapters::parsing::optional_string_field(&yaml, "description", "");
        let version =
            crate::extensions::framework::adapters::parsing::optional_string_field(&yaml, "version", "1.0.0");

        let mut manifest = ExtensionManifest::new(
            &tool_name,
            UNIVERSAL_TOOL_EXTENSION_TYPE,
            &tool_name,
            &description,
            &version,
            manifest_path
                .parent()
                .unwrap_or(Path::new("."))
                .to_path_buf(),
        );

        // Store parameters schema
        if let Some(params) = yaml.get("parameters") {
            manifest.set(
                "parameters",
                crate::extensions::framework::adapters::parsing::yaml_to_json(params.clone()),
            );
        }

        // LLM description
        if let Some(llm_desc) = yaml.get("llm_description").and_then(|v| v.as_str()) {
            manifest.set("llm_description", llm_desc);
        }

        // Reserved parameters
        if let Some(reserved) = yaml.get("reserved_parameters") {
            manifest.set(
                "reserved_parameters",
                crate::extensions::framework::adapters::parsing::yaml_to_json(reserved.clone()),
            );
        }

        Ok((manifest, tool_name))
    }

    /// Find executable for a tool (delegates to shared utility)
    async fn find_executable(&self, tool_path: &Path, tool_name: &str) -> Option<PathBuf> {
        crate::extensions::framework::adapters::parsing::find_executable(tool_path, tool_name).await
    }

    /// Register a universal tool with the unified registry (ADR-018b)
    ///
    /// This is the single canonical path for universal tool registration.
    /// `ExtensionCore::register_tool()` auto-generates companion hooks
    /// (prompt, async, status, cancel) from the metadata.
    pub async fn register_tool(
        &self,
        core: &ExtensionCore,
        manifest: &ExtensionManifest,
    ) -> Result<()> {
        let tool_name = manifest.name.clone();
        let ext_id = ExtensionId::new(format!("universal:{tool_name}"));

        // Extract description - prefer llm_description if available
        let description = manifest
            .get("llm_description")
            .and_then(|v| v.as_str())
            .map_or_else(
                || manifest.description.clone(),
                std::string::ToString::to_string,
            );

        // Extract parameters schema
        let parameters = manifest
            .get("parameters")
            .cloned()
            .unwrap_or_else(|| serde_json::json!({"type": "object"}));

        // Extract reserved parameters
        let reserved_params = manifest
            .get("reserved_parameters")
            .and_then(|v| serde_json::from_value(v.clone()).ok())
            .unwrap_or_default();

        // Create tool metadata
        let metadata = ToolMetadata::new(
            tool_name.clone(),
            description,
            parameters,
            ToolSource::Universal {
                extension_id: ext_id.0.clone(),
            },
        )
        .with_reserved_params(reserved_params);

        // Get executable path
        let executable = manifest
            .get("executable")
            .and_then(|v| v.as_str())
            .map(PathBuf::from)
            .unwrap_or_default();

        let manifest_path = manifest
            .get("manifest_path")
            .and_then(|v| v.as_str())
            .map(PathBuf::from)
            .unwrap_or_default();

        // Create execution handler (the only adapter-specific logic)
        let exec_handler = Arc::new(UniversalToolExecuteHandler {
            tool_name: tool_name.clone(),
            executable,
            manifest_path,
            full_schema: metadata.parameters.clone(),
        });

        // Register with unified registry (auto-generates all companion hooks)
        core.register_tool(metadata, exec_handler, &ext_id).await?;

        info!(tool_name = %tool_name, "Registered universal tool");
        Ok(())
    }
}

impl Default for UniversalToolAdapter {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl ExtensionTypeAdapter for UniversalToolAdapter {
    fn extension_type(&self) -> &'static str {
        UNIVERSAL_TOOL_EXTENSION_TYPE
    }

    fn manifest_format(&self) -> ManifestFormat {
        // ADR-024: Primary format is manifest.yaml with extension_type: "universal-tool".
        ManifestFormat::Yaml {
            schema: "universal-tool".to_string(),
            file_name: "manifest.yaml",
        }
    }

    fn parse_manifest(
        &self,
        path: &std::path::Path,
        content: &str,
    ) -> anyhow::Result<crate::extensions::framework::ExtensionManifest> {
        use anyhow::Context;

        // Parse as unified YAML manifest
        let yaml: serde_yaml::Value = serde_yaml::from_str(content)
            .with_context(|| format!("Failed to parse universal tool YAML manifest at {path:?}"))?;

        let tool_path = path.parent().unwrap_or(std::path::Path::new("."));
        let tool_name = crate::extensions::framework::adapters::parsing::require_string_field(&yaml, "name")
            .or_else(|_| crate::extensions::framework::adapters::parsing::require_string_field(&yaml, "id"))?;
        let description =
            crate::extensions::framework::adapters::parsing::optional_string_field(&yaml, "description", "");
        let version =
            crate::extensions::framework::adapters::parsing::optional_string_field(&yaml, "version", "1.0.0");

        let executable =
            crate::extensions::framework::adapters::parsing::find_executable_sync(tool_path, &tool_name)
                .with_context(|| {
                    format!(
                        "Failed to find executable for tool '{}' in {:?}",
                        tool_name, tool_path
                    )
                })?;

        let mut manifest = ExtensionManifest::new(
            &tool_name,
            UNIVERSAL_TOOL_EXTENSION_TYPE,
            &tool_name,
            &description,
            &version,
            tool_path.to_path_buf(),
        );

        manifest.set("executable", executable.to_string_lossy().to_string());
        manifest.set("manifest_path", path.to_string_lossy().to_string());

        // Parameters schema
        if let Some(params) = yaml.get("parameters") {
            manifest.set(
                "parameters",
                crate::extensions::framework::adapters::parsing::yaml_to_json(params.clone()),
            );
        }

        // LLM description
        if let Some(llm_desc) = yaml.get("llm_description").and_then(|v| v.as_str()) {
            manifest.set("llm_description", llm_desc);
        }

        // Reserved parameters
        if let Some(reserved) = yaml.get("reserved_parameters") {
            manifest.set(
                "reserved_parameters",
                crate::extensions::framework::adapters::parsing::yaml_to_json(reserved.clone()),
            );
        }

        Ok(manifest)
    }

    fn resolve_hooks(&self, _manifest: &ExtensionManifest) -> Vec<HookBinding> {
        // Tool-specific hooks are auto-generated by ExtensionCore::register_tool().
        // Adapters declare only non-tool lifecycle hooks here.
        vec![]
    }

    async fn register_tools(
        &self,
        core: &crate::extensions::framework::core::ExtensionCore,
        manifest: &ExtensionManifest,
    ) -> Result<usize> {
        self.register_tool(core, manifest).await?;
        Ok(1)
    }
}

/// A discovered universal tool before registration
#[derive(Debug, Clone)]
pub struct DiscoveredUniversalTool {
    /// Extension manifest
    pub manifest: ExtensionManifest,
    /// Path to executable
    pub executable: PathBuf,
    /// Path to manifest
    pub manifest_path: PathBuf,
}

// ═══════════════════════════════════════════════════════════════════════════════
// Execution Handler (the only adapter-specific hook handler)
// ═══════════════════════════════════════════════════════════════════════════════

/// Handler that executes a universal tool by spawning its external process.
#[derive(Debug, Clone)]
struct UniversalToolExecuteHandler {
    tool_name: String,
    executable: PathBuf,
    manifest_path: PathBuf,
    full_schema: serde_json::Value,
}

#[async_trait]
impl HookHandler for UniversalToolExecuteHandler {
    async fn handle(&self, ctx: HookContext) -> HookResult {
        let manifest_path = self.manifest_path.clone();
        let executable = self.executable.clone();

        let exec_config =
            crate::extensions::framework::services::ToolExecutionConfig::with_schema(self.full_schema.clone());

        ctx.services
            .async_router()
            .execute_from_hook(
                &ctx,
                &self.tool_name,
                &exec_config,
                None::<fn(&mut serde_json::Value, Option<&str>)>,
                move |merged_params| async move {
                    let adapter = crate::extensions::universal::protocol::UniversalToolAdapter::from_manifest(
                        &manifest_path,
                        &executable,
                    )
                    .await?;
                    adapter.execute_raw(merged_params).await
                },
            )
            .await
    }

    fn hook_point(&self) -> HookPoint {
        HookPoint::ToolExecute {
            tool_name: self.tool_name.clone(),
        }
    }

    fn priority(&self) -> i32 {
        UNIVERSAL_TOOL_HOOK_PRIORITY
    }

    fn name(&self) -> String {
        format!("UniversalToolExecuteHandler({})", self.tool_name)
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Helper functions
// ═══════════════════════════════════════════════════════════════════════════════

/// Load tools from directory using the adapter
pub async fn load_tools_from_directory(path: &Path) -> Vec<DiscoveredUniversalTool> {
    let adapter = UniversalToolAdapter::new();
    adapter.discover_tools(path).await
}

/// Load and register universal tools with an ExtensionCore
pub async fn load_and_register_tools(
    core: &crate::extensions::framework::ExtensionCore,
    tools_dir: impl AsRef<Path>,
) -> Result<usize> {
    let adapter = UniversalToolAdapter::new();
    let tools = adapter.discover_tools(tools_dir.as_ref()).await;
    let mut count = 0;
    for tool in tools {
        if let Err(e) = adapter.register_tool(core, &tool.manifest).await {
            warn!(tool = %tool.manifest.name, error = %e, "Failed to register universal tool");
        } else {
            count += 1;
        }
    }
    Ok(count)
}

// ═══════════════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    use tempfile::TempDir;

    fn create_test_tool(dir: &Path, name: &str, description: &str) -> PathBuf {
        let tool_dir = dir.join(name);
        std::fs::create_dir(&tool_dir).unwrap();

        let manifest = format!(
            "name: {name}\nextension_type: universal-tool\ndescription: {description}\nversion: \"1.0.0\"\nparameters:\n  type: object\n  properties:\n    input:\n      type: string\n"
        );

        let manifest_path = tool_dir.join("manifest.yaml");
        std::fs::write(&manifest_path, manifest).unwrap();

        // Create a dummy executable (script)
        let script_path = tool_dir.join(format!("{name}.py"));
        std::fs::write(&script_path, "#!/usr/bin/env python3\nprint('{}')").unwrap();

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = std::fs::metadata(&script_path).unwrap().permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&script_path, perms).unwrap();
        }

        tool_dir
    }

    #[test]
    fn test_universal_tool_adapter_manifest_format() {
        let adapter = UniversalToolAdapter::new();
        let format = adapter.manifest_format();

        assert!(matches!(format, ManifestFormat::Yaml { .. }));
    }

    #[tokio::test]
    async fn test_discover_tools() {
        let temp = TempDir::new().unwrap();

        create_test_tool(temp.path(), "tool1", "First tool");
        create_test_tool(temp.path(), "tool2", "Second tool");

        let adapter = UniversalToolAdapter::new();
        let tools = adapter.discover_tools(temp.path()).await;

        assert_eq!(tools.len(), 2);
        assert!(tools.iter().any(|t| t.manifest.name == "tool1"));
        assert!(tools.iter().any(|t| t.manifest.name == "tool2"));
    }

    #[tokio::test]
    async fn test_register_tool_via_unified_registry() {
        let temp = TempDir::new().unwrap();
        create_test_tool(temp.path(), "tool1", "First tool");
        create_test_tool(temp.path(), "tool2", "Second tool");

        let core = crate::extensions::framework::ExtensionCore::new();
        let adapter = UniversalToolAdapter::new();
        let tools = adapter.discover_tools(temp.path()).await;

        assert_eq!(tools.len(), 2);

        // Register both tools via the unified registry
        for tool in &tools {
            adapter.register_tool(&core, &tool.manifest).await.unwrap();
        }

        // Each tool registers 5 hooks (exec, prompt, async, status, cancel)
        // via the unified registry's atomic composite operation
        assert_eq!(core.hook_count().await, 10);
        assert_eq!(core.tool_count().await, 2);

        // Verify tool metadata is accessible
        let meta = core.get_tool_metadata("tool1").await;
        assert!(meta.is_some());
        assert_eq!(meta.unwrap().name, "tool1");
    }

    #[tokio::test]
    async fn test_load_and_register_tools() {
        let temp = TempDir::new().unwrap();
        create_test_tool(temp.path(), "tool1", "First tool");

        let core = crate::extensions::framework::ExtensionCore::new();
        let count = load_and_register_tools(&core, temp.path()).await.unwrap();

        assert_eq!(count, 1);
        assert_eq!(core.tool_count().await, 1);
    }
}
