//! Channel wire types — Phase 11a extension of `peko-protocol`.
//!
//! ADR-047 (slot number; assign at PR-1 merge). The full multi-principal
//! chat primitive lives in `peko-channel` (separate crate, peer of
//! `peko-cron` / `peko-quota` / `peko-protocol`); the *wire* types live
//! here so CLI / daemon / share-me can all agree on a shape without each
//! carrying its own private variant.
//!
//! ## Deps rule
//!
//! `peko-protocol` depends only on `serde` + `serde_json` (per
//! `Cargo.toml:10-12` and the lib doc on lines 5-18 of `lib.rs`). Principal
//! DIDs in this module are `String` (parsed to `peko_subject::PrincipalId`
//! at the consumer boundary). Timestamps are RFC3339 strings (the project
//! convention — see `peko_cron::ScheduleKind::At { at: String }`).
//!
//! ## Convention mirrors
//!
//! - `ChannelId` is a `String`-newtype, mirroring `peko_subject::PrincipalId`
//!   at `peko-rs/subject/src/lib.rs:25-27`.
//! - `ChannelEvent` is a tagged enum with `tag = "kind"` and
//!   `rename_all = "snake_case"`, mirroring `peko_cron::ScheduleKind` at
//!   `peko-rs/cron/src/tools/mod.rs:54-56`.
//! - Round-trip tests at the bottom pin exact JSON literals, mirroring
//!   `peko-rs/protocol/src/ipc.rs:81-107`.

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// ChannelId
// ---------------------------------------------------------------------------

/// Channel identifier. Opaque `String` newtype.
///
/// Wire shapes (any of four forms — see [`ChannelKind`]):
///
/// | Wire form             | Kind       | Semantics                                          |
/// |-----------------------|------------|----------------------------------------------------|
/// | `chan_<8 base36>`     | `Bare`     | Plain fire-and-forget post                         |
/// | `principal:<did>`     | `Principal`| RPC: auto-provision DM, await reply up to 1 min   |
/// | `user:<id>`           | `User`     | Fire-and-forget note to a user                    |
/// | `group:<slug>`        | `Group`    | Fire-and-forget post to a group                   |
///
/// Bare ids are generated by [`ChannelId::generate`]; typed ids are
/// minted via [`ChannelId::for_principal`] / [`ChannelId::for_user`] /
/// [`ChannelId::for_group`]. [`ChannelId::parse`] accepts any of the
/// four forms. The inner field serializes directly to a JSON string
/// (no `#[serde(transparent)]` — the project doesn't use it, matching
/// `peko_subject::PrincipalId`).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ChannelId(pub String);

/// Dispatch kind for a [`ChannelId`]. The runtime branches on this to
/// select the right tool semantics (RPC vs fire-and-forget). Derived
/// from the channel-id prefix; see [`ChannelId::kind`].
///
/// `Serialize` / `Deserialize` are deliberately omitted — this is a
/// runtime-only dispatch enum, not a wire type. The wire form is the
/// `ChannelId` itself.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ChannelKind {
    /// `chan_<8 base36>` — plain fire-and-forget post.
    Bare,
    /// `principal:<did>` — RPC: auto-provision DM channel, await reply.
    Principal,
    /// `user:<id>` — fire-and-forget note to a user (originating-user
    /// gate enforced at the messenger port, not here).
    User,
    /// `group:<slug>` — fire-and-forget post to a group.
    Group,
}

impl ChannelKind {
    /// Wire prefix for this kind. Mirrors the prefix consumed by
    /// [`ChannelId::parse`].
    pub const fn prefix(self) -> &'static str {
        match self {
            Self::Bare => "chan_",
            Self::Principal => "principal:",
            Self::User => "user:",
            Self::Group => "group:",
        }
    }
}

impl ChannelId {
    /// Prefix for randomly-generated bare channel ids. Mirrors
    /// `peko_plan::NodeId::PREFIX`.
    pub const PREFIX: &'static str = "chan_";

    /// Length of the random suffix. Eight base36 chars gives 36^8 ≈ 2.8T
    /// possibilities — the same entropy budget used by `peko_plan::NodeId`
    /// (`schema.rs:49`) and `peko_plan::PlanRecord::plan_id` (`schema.rs:143`).
    const SUFFIX_LEN: usize = 8;

    /// Generate a fresh, unique bare id. Uses the same splitmix64-style
    /// entropy mixing as `peko_plan::schema::rand_u32` (`schema.rs:485-504`).
    pub fn generate() -> Self {
        Self(format!("{}{}", Self::PREFIX, generate_base36_suffix()))
    }

    /// Build a principal-DM channel id from a DID. Wire form:
    /// `principal:<did>`. No BLAKE3 needed — the DID itself is already
    /// cross-runtime-stable, so both sides of a `send_peer` exchange
    /// independently derive the same channel id from the same DID.
    pub fn for_principal(did: &str) -> Self {
        debug_assert!(!did.is_empty(), "for_principal: DID must not be empty");
        Self(format!("principal:{did}"))
    }

    /// Build a user-channel id from a free-form user id. Wire form:
    /// `user:<id>`. The originating-user gate (only the user who
    /// started the current run may be addressed) lives at the
    /// messenger-port layer, not in the id.
    pub fn for_user(id: &str) -> Self {
        debug_assert!(!id.is_empty(), "for_user: id must not be empty");
        Self(format!("user:{id}"))
    }

    /// Build a group-channel id from a free-form slug. Wire form:
    /// `group:<slug>`. The LLM picks the slug (matches today's
    /// `chan_<random>` semantics where the LLM picks the bare
    /// identifier). Prelaunch; cross-principal collisions on the
    /// shared tier are accepted.
    pub fn for_group(slug: &str) -> Self {
        debug_assert!(!slug.is_empty(), "for_group: slug must not be empty");
        Self(format!("group:{slug}"))
    }

    /// Dispatch kind. Pure-string prefix dispatch on the inner
    /// `String`; no allocation.
    pub fn kind(&self) -> ChannelKind {
        if self.0.starts_with("principal:") {
            ChannelKind::Principal
        } else if self.0.starts_with("user:") {
            ChannelKind::User
        } else if self.0.starts_with("group:") {
            ChannelKind::Group
        } else {
            // The default kind is `Bare` for `chan_<...>` ids AND for any
            // unrecognized prefix — `parse` rejects unknown prefixes at
            // the boundary, so a `ChannelId` constructed via the public
            // API always matches one of these four cases at runtime.
            ChannelKind::Bare
        }
    }

    /// Parse a string back into a `ChannelId`, validating the prefix
    /// and (for the bare form) the 8 base36 suffix. Accepts any of the
    /// four wire forms; rejects unknown prefixes and empty
    /// post-prefix content. Returns `None` (rather than erroring) so
    /// callers in deserialize paths can decide to skip unknown ids.
    pub fn parse(s: &str) -> Option<Self> {
        if let Some(rest) = s.strip_prefix(Self::PREFIX) {
            return Self::parse_chan(rest);
        }
        if let Some(rest) = s.strip_prefix(ChannelKind::Principal.prefix()) {
            return Self::parse_typed(ChannelKind::Principal.prefix(), rest);
        }
        if let Some(rest) = s.strip_prefix(ChannelKind::User.prefix()) {
            return Self::parse_typed(ChannelKind::User.prefix(), rest);
        }
        if let Some(rest) = s.strip_prefix(ChannelKind::Group.prefix()) {
            return Self::parse_typed(ChannelKind::Group.prefix(), rest);
        }
        None
    }

    /// Validate the bare-form suffix. Preserved byte-for-byte from the
    /// pre-typed-prefix implementation; the dead-code structure
    /// (`is_ascii_hexdigit && !is_ascii_uppercase`) was an awkward
    /// way to say "0-9a-z" that shipped prelaunch and is pinned by
    /// `channel_id_parse_rejects_invalid`. Out of scope for this PR.
    fn parse_chan(rest: &str) -> Option<Self> {
        if rest.len() != Self::SUFFIX_LEN {
            return None;
        }
        if !rest.bytes().all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase()) {
            // accept 0-9a-z only (matches peko-plan's BASE36)
            let valid = rest
                .bytes()
                .all(|b| b.is_ascii_digit() || b.is_ascii_lowercase());
            if !valid {
                return None;
            }
        }
        Some(Self(format!("{}{}", Self::PREFIX, rest)))
    }

    /// Validate a typed-prefix form: post-prefix content must be
    /// non-empty. No further format check (the DID / user-id / slug
    /// grammar is enforced at the consumer boundary — `ChannelId`
    /// remains an opaque string).
    fn parse_typed(prefix: &str, rest: &str) -> Option<Self> {
        if rest.is_empty() {
            return None;
        }
        Some(Self(format!("{prefix}{rest}")))
    }

    /// Borrow the inner string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for ChannelId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

// ---------------------------------------------------------------------------
// ChannelEvent
// ---------------------------------------------------------------------------

/// Causal-ordered event log for one channel.
///
/// Wire shape (one example per variant):
///
/// ```json
/// {"kind":"created","channel":"chan_a1b2c3d4","creator":"prin_xyz","name":"design-sync","at":"2026-08-05T12:00:00Z"}
/// {"kind":"posted","channel":"chan_a1b2c3d4","author":"prin_xyz","parent":null,"text":"hi","at":"2026-08-05T12:01:00Z"}
/// {"kind":"posted","channel":"chan_a1b2c3d4","author":"prin_qrs","parent":"node_xyz12345","text":"reply","at":"2026-08-05T12:02:00Z"}
/// {"kind":"member_joined","channel":"chan_a1b2c3d4","member":"prin_qrs","at":"2026-08-05T12:00:30Z"}
/// {"kind":"member_left","channel":"chan_a1b2c3d4","member":"prin_qrs","at":"2026-08-05T12:30:00Z"}
/// ```
///
/// `parent` carries a `peko_plan::NodeId` opaque-string reference to the
/// message being replied to; `null` for root posts (the adapter enforces
/// at-most-one parent — see `peko_channel::plan_channel`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum ChannelEvent {
    /// Channel creation. Fires once at the top of the event log.
    Created {
        channel: ChannelId,
        creator: String,
        name: String,
        at: String,
    },
    /// A message authored by `author`. `parent` references the prior
    /// message being replied to; `None` for the channel's first post.
    Posted {
        channel: ChannelId,
        author: String,
        parent: Option<String>,
        text: String,
        at: String,
    },
    /// A principal was invited / joined the channel. Append-only — a
    /// subsequent `MemberLeft` carries the inverse.
    MemberJoined {
        channel: ChannelId,
        member: String,
        at: String,
    },
    /// A principal left (or was removed from) the channel.
    MemberLeft {
        channel: ChannelId,
        member: String,
        at: String,
    },
}

impl ChannelEvent {
    /// Wire-tag discriminant. Mirrors `CronJobAction::kind_label` at
    /// `peko-rs/cron/src/tools/mod.rs:158-165`.
    pub fn kind(&self) -> &'static str {
        match self {
            Self::Created { .. } => "created",
            Self::Posted { .. } => "posted",
            Self::MemberJoined { .. } => "member_joined",
            Self::MemberLeft { .. } => "member_left",
        }
    }
}

// ---------------------------------------------------------------------------
// ChannelMembership — IPC response snapshot
// ---------------------------------------------------------------------------

/// Snapshot of channel membership for IPC responses. The authoritative
/// source of "who is currently a member" is the event log
/// (`MemberJoined` minus `MemberLeft`); this struct is the precomputed
/// answer for callers that don't want to walk the log.
///
/// Mirrors `peko_cron::CronJob`'s flat-struct convention
/// (`peko-rs/cron/src/tools/mod.rs:181-219`): snake_case fields, no
/// `tag`, `Option` fields use `default` + `skip_serializing_if = "is_none"`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct ChannelMembership {
    pub channel: ChannelId,
    pub name: String,
    pub creator: String,
    pub members: Vec<String>,
    /// P1.2 attribution: per-member runtime provenance (local vs
    /// remote). Empty for channels with no remote members; legacy
    /// pre-PR-3b implementations may omit the field entirely
    /// (`#[serde(default)]`).
    #[serde(default)]
    pub member_provenance: Vec<MemberProvenance>,
    /// RFC3339 timestamp of the channel's `Created` event.
    pub created_at: String,
    /// RFC3339 timestamp of the most recent `Member*` event affecting
    /// the membership set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_membership_change: Option<String>,
}

/// P1.2 attribution: pairs a principal DID with its hosting runtime
/// id. `runtime_id: None` means the principal is local to the
/// receiving runtime; `Some(runtime_id)` means the principal is hosted
/// on a peer runtime that joined the channel via the cross-runtime
/// invite envelope.
///
/// The flat `ChannelMembership::members` list is the back-compat
/// surface; `MemberProvenance` is the richer shape that lets the UI
/// render local vs remote members distinctly. Pre-PR-3b consumers
/// that don't read `member_provenance` see no change to the wire
/// shape — the field uses `#[serde(default)]` and skips when empty.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct MemberProvenance {
    pub principal: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_id: Option<String>,
}

// ---------------------------------------------------------------------------
// InitialMember — peko-channel cross-runtime PR-3a commit 1
// ---------------------------------------------------------------------------

/// One row of the `initialMembers` list on
/// [`crate::tunnel::TunnelChannelInvite`] (the source runtime's
/// fan-out of a channel invite to a remote runtime's hosting
/// runtime). Pairs a principal DID with the runtime that hosts it.
///
/// Wire shape:
///
/// ```json
/// {"principalDid":"prin_alice"}
/// {"principalDid":"prin_bob","runtimeId":"did:key:zRuntimeB"}
/// ```
///
/// `runtime_id: None` means the principal is local to the source
/// runtime — the receiver should land the row in
/// `members.json`'s local array. `runtime_id: Some(id)` means the
/// principal lives on a peer runtime and the receiver should
/// record a `RemoteMember` row.
///
/// `#[serde(skip_serializing_if = "Option::is_none")]` on
/// `runtime_id` keeps the wire form minimal for the common
/// (single-runtime) case: a 4-line bootstrap envelope shrinks by
/// ~22 bytes per local member. Verified by
/// [`initial_member_skips_none_runtime_id`].
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InitialMember {
    pub principal_did: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_id: Option<String>,
}

// ---------------------------------------------------------------------------
// Internal: 8-char lowercase base36 id suffix
// ---------------------------------------------------------------------------

const BASE36: &[u8] = b"0123456789abcdefghijklmnopqrstuvwxyz";

/// Same splitmix64-style mixing as `peko_plan::schema::rand_u32`
/// (`schema.rs:485-504`). Wall-clock nanos + monotonic counter + pid —
/// enough for `chan_<8 base36>` ids within a single process lifetime.
fn generate_base36_suffix() -> String {
    use std::sync::atomic::{AtomicU64, Ordering};
    static CTR: AtomicU64 = AtomicU64::new(0);

    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0);
    let pid = std::process::id() as u64;
    let ctr = CTR.fetch_add(1, Ordering::Relaxed);

    let mut z = now
        .wrapping_add(ctr.wrapping_mul(0x9E3779B97F4A7C15))
        .wrapping_add(pid.wrapping_mul(0xBF58476D1CE4E5B9));
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
    z ^= z >> 31;
    let v = (z as u32) ^ ((z >> 32) as u32);

    let mut out = [b'0'; ChannelId::SUFFIX_LEN];
    let mut cur = v;
    for slot in out.iter_mut().rev() {
        *slot = BASE36[(cur % 36) as usize];
        cur /= 36;
    }
    String::from_utf8(out.to_vec()).expect("BASE36 is valid ASCII")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn chan() -> ChannelId {
        ChannelId("chan_abcdefgh".into())
    }

    // ----- ChannelEvent round-trips with literal-pinned JSON -----

    /// Pin the exact wire shape of `ChannelEvent::Created`. Any future
    /// rename or reordering of fields surfaces here, not at the CLI.
    #[test]
    fn channel_event_created_round_trip() {
        let ev = ChannelEvent::Created {
            channel: chan(),
            creator: "prin_alice".into(),
            name: "design-sync".into(),
            at: "2026-08-05T12:00:00Z".into(),
        };
        let expected = r#"{"kind":"created","channel":"chan_abcdefgh","creator":"prin_alice","name":"design-sync","at":"2026-08-05T12:00:00Z"}"#;
        assert_eq!(serde_json::to_string(&ev).unwrap(), expected);
        let back: ChannelEvent = serde_json::from_str(expected).unwrap();
        assert_eq!(format!("{:?}", back), format!("{:?}", ev));
    }

    /// Pin `Posted` with `parent: null` (root post).
    #[test]
    fn channel_event_posted_root_round_trip() {
        let ev = ChannelEvent::Posted {
            channel: chan(),
            author: "prin_alice".into(),
            parent: None,
            text: "hello".into(),
            at: "2026-08-05T12:01:00Z".into(),
        };
        let expected = r#"{"kind":"posted","channel":"chan_abcdefgh","author":"prin_alice","parent":null,"text":"hello","at":"2026-08-05T12:01:00Z"}"#;
        assert_eq!(serde_json::to_string(&ev).unwrap(), expected);
    }

    /// Pin `Posted` with `parent: Some("node_xyz12345")`.
    #[test]
    fn channel_event_posted_with_parent_round_trip() {
        let ev = ChannelEvent::Posted {
            channel: chan(),
            author: "prin_bob".into(),
            parent: Some("node_xyz12345".into()),
            text: "reply".into(),
            at: "2026-08-05T12:02:00Z".into(),
        };
        let expected = r#"{"kind":"posted","channel":"chan_abcdefgh","author":"prin_bob","parent":"node_xyz12345","text":"reply","at":"2026-08-05T12:02:00Z"}"#;
        assert_eq!(serde_json::to_string(&ev).unwrap(), expected);
    }

    /// Pin `MemberJoined`.
    #[test]
    fn channel_event_member_joined_round_trip() {
        let ev = ChannelEvent::MemberJoined {
            channel: chan(),
            member: "prin_bob".into(),
            at: "2026-08-05T12:00:30Z".into(),
        };
        let expected = r#"{"kind":"member_joined","channel":"chan_abcdefgh","member":"prin_bob","at":"2026-08-05T12:00:30Z"}"#;
        assert_eq!(serde_json::to_string(&ev).unwrap(), expected);
    }

    /// Pin `MemberLeft`.
    #[test]
    fn channel_event_member_left_round_trip() {
        let ev = ChannelEvent::MemberLeft {
            channel: chan(),
            member: "prin_bob".into(),
            at: "2026-08-05T12:30:00Z".into(),
        };
        let expected = r#"{"kind":"member_left","channel":"chan_abcdefgh","member":"prin_bob","at":"2026-08-05T12:30:00Z"}"#;
        assert_eq!(serde_json::to_string(&ev).unwrap(), expected);
    }

    /// `kind()` returns the wire-tag discriminant for non-serde callers.
    /// Mirrors `CronJobAction::kind_label`.
    #[test]
    fn channel_event_kind_helper() {
        let cases = [
            (ChannelEvent::Created { channel: chan(), creator: "p".into(), name: "n".into(), at: "2026".into() }, "created"),
            (ChannelEvent::Posted { channel: chan(), author: "p".into(), parent: None, text: "t".into(), at: "2026".into() }, "posted"),
            (ChannelEvent::MemberJoined { channel: chan(), member: "p".into(), at: "2026".into() }, "member_joined"),
            (ChannelEvent::MemberLeft { channel: chan(), member: "p".into(), at: "2026".into() }, "member_left"),
        ];
        for (ev, expected) in cases {
            assert_eq!(ev.kind(), expected, "kind() mismatch for {ev:?}");
        }
    }

    // ----- ChannelId -----

    #[test]
    fn channel_id_generate_has_prefix() {
        let id = ChannelId::generate();
        assert!(id.as_str().starts_with(ChannelId::PREFIX));
        assert_eq!(id.as_str().len(), ChannelId::PREFIX.len() + ChannelId::SUFFIX_LEN);
    }

    #[test]
    fn channel_id_parse_round_trip() {
        let id = ChannelId::generate();
        let parsed = ChannelId::parse(id.as_str()).expect("parse generated id");
        assert_eq!(parsed, id);
    }

    #[test]
    fn channel_id_parse_rejects_invalid() {
        // Wrong prefix
        assert!(ChannelId::parse("node_abcdefgh").is_none());
        assert!(ChannelId::parse("chan_").is_none());
        // Wrong suffix length (too short)
        assert!(ChannelId::parse("chan_abc").is_none());
        // Wrong suffix length (too long)
        assert!(ChannelId::parse("chan_abcdefghi").is_none());
        // Uppercase rejected
        assert!(ChannelId::parse("chan_ABCDEFGH").is_none());
        // Non-base36 char
        assert!(ChannelId::parse("chan_abc!defg").is_none());
    }

    #[test]
    fn channel_id_wire_serializes_as_bare_string() {
        let id = ChannelId("chan_xyz12345".into());
        let json = serde_json::to_string(&id).unwrap();
        // No transparent attribute needed; `pub String` field emits directly.
        assert_eq!(json, r#""chan_xyz12345""#);
        let back: ChannelId = serde_json::from_str(&json).unwrap();
        assert_eq!(back, id);
    }

    // ----- ChannelKind prefix constants -----

    /// `ChannelKind::prefix` is the wire prefix consumed by
    /// `ChannelId::parse`. Drift here breaks the dispatch table.
    #[test]
    fn channel_kind_prefix_constants_match_parse_arms() {
        assert_eq!(ChannelKind::Bare.prefix(), "chan_");
        assert_eq!(ChannelKind::Principal.prefix(), "principal:");
        assert_eq!(ChannelKind::User.prefix(), "user:");
        assert_eq!(ChannelKind::Group.prefix(), "group:");
    }

    // ----- ChannelId::kind dispatch -----

    /// `kind()` is a pure-string prefix dispatch on the inner `String`.
    /// All four wire forms return the expected variant. No allocation
    /// beyond the prefix comparisons.
    #[test]
    fn channel_id_kind_dispatches_each_form() {
        let cases = [
            ("chan_a1b2c3d4", ChannelKind::Bare),
            ("principal:did:key:zAlice", ChannelKind::Principal),
            ("user:alice", ChannelKind::User),
            ("group:eng-standup", ChannelKind::Group),
        ];
        for (raw, expected) in cases {
            let id = ChannelId::parse(raw).expect("parse should succeed");
            assert_eq!(id.kind(), expected, "kind() mismatch for {raw}");
        }
    }

    /// `kind()` matches the constructor that minted the id. Pins
    /// forward and inverse agreement between constructors and the
    /// string-dispatch helper.
    #[test]
    fn channel_id_kind_matches_constructor() {
        assert_eq!(ChannelId::for_principal("did:key:zAlice").kind(), ChannelKind::Principal);
        assert_eq!(ChannelId::for_user("alice").kind(), ChannelKind::User);
        assert_eq!(ChannelId::for_group("eng-standup").kind(), ChannelKind::Group);
        assert_eq!(ChannelId::generate().kind(), ChannelKind::Bare);
    }

    // ----- ChannelId::parse typed-prefix arms -----

    /// `parse` accepts `principal:<did>` with arbitrary inner content.
    /// The DID grammar is enforced at the consumer boundary
    /// (`peko_subject::PrincipalId::parse`), not here.
    #[test]
    fn channel_id_parse_accepts_principal_prefix() {
        let id = ChannelId::parse("principal:did:key:zAlice").expect("principal: should parse");
        assert_eq!(id.as_str(), "principal:did:key:zAlice");
        // Round-trip through serialization: the bare-string field
        // emits the full wire form, no transform.
        let json = serde_json::to_string(&id).unwrap();
        assert_eq!(json, r#""principal:did:key:zAlice""#);
        let back: ChannelId = serde_json::from_str(&json).unwrap();
        assert_eq!(back, id);
    }

    /// `parse` accepts `user:<id>` with arbitrary inner content.
    #[test]
    fn channel_id_parse_accepts_user_prefix() {
        let id = ChannelId::parse("user:alice").expect("user: should parse");
        assert_eq!(id.as_str(), "user:alice");
    }

    /// `parse` accepts `group:<slug>` with arbitrary inner content.
    #[test]
    fn channel_id_parse_accepts_group_prefix() {
        let id = ChannelId::parse("group:eng-standup").expect("group: should parse");
        assert_eq!(id.as_str(), "group:eng-standup");
    }

    /// `parse` rejects `principal:` with no post-prefix content. The
    /// DID is required; an empty body would route to a degenerate
    /// state that breaks the dispatch table.
    #[test]
    fn channel_id_parse_rejects_empty_post_prefix() {
        assert!(ChannelId::parse("principal:").is_none());
        assert!(ChannelId::parse("user:").is_none());
        assert!(ChannelId::parse("group:").is_none());
    }

    /// `parse` rejects unknown prefixes entirely. A wire form like
    /// `local:<x>` or `peer:<x>` cannot sneak through into the
    /// dispatch table — `kind()` defaults to `Bare` only for the
    /// `chan_<...>` form; anything else fails parsing.
    #[test]
    fn channel_id_parse_rejects_unknown_prefix() {
        assert!(ChannelId::parse("local:foo").is_none());
        assert!(ChannelId::parse("peer:foo").is_none());
        assert!(ChannelId::parse("dm:foo").is_none());
        assert!(ChannelId::parse("").is_none());
    }

    // ----- ChannelId typed-prefix constructors -----

    /// `for_principal` produces a deterministic id from the DID; the
    /// DID itself is cross-runtime-stable so no BLAKE3 / hash step is
    /// needed for both sides of a `send_peer` exchange to derive the
    /// same id.
    #[test]
    fn channel_id_for_principal_is_deterministic() {
        let a = ChannelId::for_principal("did:key:zAlice");
        let b = ChannelId::for_principal("did:key:zAlice");
        assert_eq!(a, b, "same DID must mint same id");
        assert_eq!(a.as_str(), "principal:did:key:zAlice");
    }

    /// `for_user` and `for_group` are deterministic per-input.
    #[test]
    fn channel_id_for_user_and_group_are_deterministic() {
        assert_eq!(ChannelId::for_user("alice").as_str(), "user:alice");
        assert_eq!(ChannelId::for_group("eng-standup").as_str(), "group:eng-standup");
    }

    /// Round-trip: every constructor → parse → constructor produces
    /// an equal id. The constructor / parser pair must agree on every
    /// wire form.
    #[test]
    fn channel_id_constructor_round_trips_through_parse() {
        let cases = [
            ChannelId::for_principal("did:key:zAlice"),
            ChannelId::for_user("alice"),
            ChannelId::for_group("eng-standup"),
            ChannelId::generate(),
        ];
        for id in cases {
            let parsed = ChannelId::parse(id.as_str()).expect("constructor output must parse");
            assert_eq!(parsed, id, "round-trip failed for {}", id.as_str());
        }
    }

    // ----- ChannelMembership -----

    #[test]
    fn channel_membership_round_trip() {
        let m = ChannelMembership {
            channel: chan(),
            name: "design".into(),
            creator: "prin_alice".into(),
            members: vec!["prin_alice".into(), "prin_bob".into()],
            member_provenance: vec![],
            created_at: "2026-08-05T12:00:00Z".into(),
            last_membership_change: Some("2026-08-05T12:00:30Z".into()),
        };
        let json = serde_json::to_string(&m).unwrap();
        let back: ChannelMembership = serde_json::from_str(&json).unwrap();
        assert_eq!(back, m);
    }

    /// `last_membership_change: None` is omitted from the wire to keep
    /// the IPC response minimal for newly-created channels.
    #[test]
    fn channel_membership_skips_none_change_field() {
        let m = ChannelMembership {
            channel: chan(),
            name: "design".into(),
            creator: "prin_alice".into(),
            members: vec!["prin_alice".into()],
            member_provenance: vec![],
            created_at: "2026-08-05T12:00:00Z".into(),
            last_membership_change: None,
        };
        let json = serde_json::to_string(&m).unwrap();
        assert!(!json.contains("last_membership_change"), "got {json}");
        let back: ChannelMembership = serde_json::from_str(&json).unwrap();
        assert_eq!(back.last_membership_change, None);
    }

    // ----- InitialMember — peko-channel cross-runtime PR-3a commit 1 -----

    /// `InitialMember` with `runtime_id: Some(...)` round-trips with
    /// camelCase fields. Pins the contract with the tunnel-protocol
    /// envelope + the hub-side relay.
    #[test]
    fn initial_member_remote_round_trip() {
        let m = InitialMember {
            principal_did: "prin_bob".to_string(),
            runtime_id: Some("did:key:zRuntimeB".to_string()),
        };
        let json = serde_json::to_string(&m).unwrap();
        assert!(
            json.contains("\"principalDid\""),
            "principalDid must be camelCase; got: {json}"
        );
        assert!(
            json.contains("\"runtimeId\""),
            "runtimeId must be camelCase; got: {json}"
        );
        let back: InitialMember = serde_json::from_str(&json).unwrap();
        assert_eq!(back, m);
    }

    /// `runtime_id: None` is skipped on the wire — not serialized as
    /// `null`. This matters for the tunnel pre-image: serde_json
    /// emits a single canonical byte sequence, so the signer and
    /// verifier must see the same bytes. Verified by re-serializing
    /// after a round-trip (the `serde_json::from_str` + `to_string`
    /// pair must be idempotent for the skipped field).
    #[test]
    fn initial_member_skips_none_runtime_id() {
        let m = InitialMember {
            principal_did: "prin_alice".to_string(),
            runtime_id: None,
        };
        let json = serde_json::to_string(&m).unwrap();
        assert!(
            !json.contains("runtimeId"),
            "runtime_id=None must be skipped, got: {json}"
        );
        let back: InitialMember = serde_json::from_str(&json).unwrap();
        assert_eq!(back, m);
        // Re-serializing the round-tripped value must produce the
        // same bytes (the canonical pre-image the tunnel signature
        // signs).
        let re_json = serde_json::to_string(&back).unwrap();
        assert_eq!(re_json, json, "round-trip must be byte-stable");
    }
}
