//! MCP (Model Context Protocol) Adapter for the Extension system
//!
//! This adapter integrates MCP servers into the unified Extension Architecture.
//! MCP servers are stateful (maintain connections) and can provide tools,
//! resources, and prompts.
//!
//! # MCP Server Format
//!
//! MCP servers are configured via `server.json` (Tier 1) or `manifest.yaml`
//! with `extension_type: "mcp"` (Tier 2), or discovered from the
//! `mcp_servers/` directory:
//! ```toml
//! [[servers]]
//! name = "filesystem"
//! transport = "stdio"
//! command = "npx"
//! args = ["-y", "@modelcontextprotocol/server-filesystem", "/path"]
//! auto_start = true
//! ```
//!
//! # Registration
//!
//! MCP tools are registered via the unified registry (`ExtensionCore::register_tool()`).
//! Companion hooks (prompt, async, status, cancel) are auto-generated by the
//! registry per individual tool.  This adapter only supplies the execution handler.
//!
//! Lifecycle hooks (AgentInit, AgentShutdown) are still declared via
//! `resolve_hooks()` because they are server-level, not tool-level.

use crate::extensions::framework::adapters::{
    ExtensionState, ExtensionTypeAdapter, ManifestFormat,
};
use crate::extensions::framework::core::{
    ExtensionCore, HookBinding, HookContext, HookHandler, HookHandlerFactory, HookPoint,
    ToolMetadata, ToolSource,
};
use crate::extensions::framework::types::{ExtensionId, ExtensionManifest, HookOutput, HookResult};
use crate::subject::PrincipalId;
use anyhow::{Context, Result};
use async_trait::async_trait;
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock};
use tokio::sync::RwLock;
use tracing::{debug, info, warn};

/// MCP extension type identifier
pub const MCP_EXTENSION_TYPE: &str = "mcp";

/// Default priority for MCP hooks
pub const MCP_HOOK_PRIORITY: i32 = 50;

/// Prefix for MCP tool names
pub const MCP_TOOL_PREFIX: &str = "mcp";

/// Global MCP manager instance shared across all adapters
static GLOBAL_MCP_MANAGER: OnceLock<
    Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
> = OnceLock::new();

/// Get or initialize the global MCP manager (standalone mode).
fn get_global_mcp_manager() -> Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>> {
    GLOBAL_MCP_MANAGER
        .get_or_init(|| {
            let config = crate::extensions::mcp::protocol::config::McpConfig::default();
            Arc::new(RwLock::new(
                crate::extensions::mcp::protocol::manager::McpManager::new(config),
            ))
        })
        .clone()
}

/// Initialize the global MCP manager with shared daemon resources.
///
/// This should be called once during daemon startup **before** any code
/// calls `McpAdapter::with_default_manager()`.  After this call the global
/// manager will use the daemon-wide `BackgroundRuntimeManager` and
/// `McpClientRegistry` so that `ext start` / `ext stop` control the same
/// runtimes that agent-init and tool-proxy code paths see.
pub fn init_global_mcp_manager_with_shared_resources(
    runtime_manager: Arc<crate::daemon::background_runtime::BackgroundRuntimeManager>,
    client_registry: Arc<crate::extensions::mcp::runtime::McpClientRegistry>,
    llm_resolver: Option<Arc<peko_providers::LlmResolver>>,
    vault: Option<Arc<crate::common::vault::Vault>>,
    // F19: principal manager so the MCP manager can resolve per-
    // principal quota meters for sampling attribution. Optional so
    // tests can omit it.
    principal_manager: Option<Arc<crate::principal::manager::PrincipalManager>>,
) {
    let config = crate::extensions::mcp::protocol::config::McpConfig::default();
    let manager = crate::extensions::mcp::protocol::manager::McpManager::with_shared_resources(
        config,
        runtime_manager,
        client_registry,
        llm_resolver,
        vault,
    );
    let mut manager = manager;
    if let Some(pm) = principal_manager {
        manager = manager.with_principal_manager(pm);
    }
    let _ = GLOBAL_MCP_MANAGER.set(Arc::new(RwLock::new(manager)));
}

/// MCP adapter for Extension system
pub struct McpAdapter {
    /// Shared MCP manager for all servers
    manager: Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
}

impl std::fmt::Debug for McpAdapter {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("McpAdapter")
            .field("manager", &"<McpManager>")
            .finish()
    }
}

impl McpAdapter {
    /// Create a new MCP adapter
    pub fn new(
        manager: Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
    ) -> Self {
        Self { manager }
    }

    /// Create a new MCP adapter with the global shared manager
    #[must_use]
    pub fn with_default_manager() -> Self {
        Self {
            manager: get_global_mcp_manager(),
        }
    }

    /// Create a new MCP adapter with a fresh manager (for testing only)
    #[cfg(test)]
    #[must_use]
    pub fn with_fresh_manager() -> Self {
        let config = crate::extensions::mcp::protocol::config::McpConfig::default();
        let manager = Arc::new(RwLock::new(
            crate::extensions::mcp::protocol::manager::McpManager::new(config),
        ));
        Self { manager }
    }

    /// Discover MCP servers from a directory
    pub async fn discover_servers(&self, path: &Path) -> Vec<DiscoveredMcpServer> {
        let mut servers = Vec::new();

        if !path.exists() {
            debug!("MCP servers directory does not exist: {:?}", path);
            return servers;
        }

        let entries = match tokio::fs::read_dir(path).await {
            Ok(entries) => entries,
            Err(e) => {
                warn!("Failed to read MCP directory {:?}: {}", path, e);
                return servers;
            }
        };

        let mut dir_entries = Vec::new();
        let mut entries = entries;
        while let Ok(Some(entry)) = entries.next_entry().await {
            dir_entries.push(entry);
        }

        for entry in dir_entries {
            let path = entry.path();
            let name = entry.file_name();
            let name_str = name.to_string_lossy();

            if name_str.starts_with('.') {
                continue;
            }

            let manifest_path = if path.is_dir() {
                let server_json = path.join("server.json");
                let manifest_yaml = path.join("manifest.yaml");
                if server_json.exists() {
                    server_json
                } else if manifest_yaml.exists() {
                    manifest_yaml
                } else {
                    continue;
                }
            } else {
                path.clone()
            };

            let content = match tokio::fs::read_to_string(&manifest_path).await {
                Ok(c) => c,
                Err(e) => {
                    warn!("Failed to read MCP manifest {:?}: {}", manifest_path, e);
                    continue;
                }
            };

            match self.parse_manifest(&manifest_path, &content) {
                Ok(manifest) => {
                    servers.push(DiscoveredMcpServer {
                        manifest,
                        config_path: manifest_path.clone(),
                        server_dir: if path.is_dir() {
                            path.clone()
                        } else {
                            path.parent().unwrap_or(Path::new(".")).to_path_buf()
                        },
                    });
                }
                Err(e) => {
                    warn!("Failed to parse MCP manifest {:?}: {}", manifest_path, e);
                }
            }
        }

        servers
    }

    /// Load server config from a file
    async fn load_server_config(
        path: &Path,
    ) -> Result<crate::extensions::mcp::protocol::config::McpServerConfig> {
        let content = tokio::fs::read_to_string(path)
            .await
            .with_context(|| format!("Failed to read config {path:?}"))?;

        let server_configs: Vec<crate::extensions::mcp::protocol::config::McpServerConfig> =
            if path.extension().is_some_and(|e| e == "toml") {
                let config: crate::extensions::mcp::protocol::config::McpConfig =
                    toml::from_str(&content)
                        .with_context(|| format!("Failed to parse TOML config {path:?}"))?;
                config.servers
            } else {
                let config: crate::extensions::mcp::protocol::config::McpConfig =
                    serde_json::from_str(&content)
                        .with_context(|| format!("Failed to parse JSON config {path:?}"))?;
                config.servers
            };

        server_configs
            .into_iter()
            .next()
            .ok_or_else(|| anyhow::anyhow!("No server configurations found in config file"))
    }

    /// Get the MCP manager
    #[must_use]
    pub fn manager(&self) -> Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>> {
        self.manager.clone()
    }

    /// Ensure server config is loaded into the MCP manager
    pub async fn ensure_server_config(&self, config_path: &str) -> Result<()> {
        let path = Path::new(config_path);
        let mut server_config = Self::load_server_config(path).await?;
        let server_name = server_config.name.clone();

        if server_config.cwd.is_none() {
            server_config.cwd = path.parent().map(std::path::Path::to_path_buf);
            if let Some(ref cwd) = server_config.cwd {
                info!(server_name = %server_name, cwd = %cwd.display(), "Set MCP server working directory");
            }
        }

        let manager = self.manager.read().await;
        let exists = manager.get_server_state(&server_name).await.is_ok();
        drop(manager);

        if !exists {
            let manager = self.manager.read().await;
            manager.add_server_config(server_config).await?;
            info!(server_name = %server_name, "Added MCP server config to manager");
        }

        Ok(())
    }

    /// Ensure server config from unified manifest `mcp_servers` data.
    ///
    /// ADR-024: Unified manifest embeds MCP server config under `mcp_servers:`
    /// rather than a separate config file. This method extracts each server
    /// definition and loads it into the MCP manager.
    pub async fn ensure_server_config_from_manifest(
        &self,
        manifest: &ExtensionManifest,
    ) -> Result<()> {
        let mcp_servers = manifest
            .get("mcp_servers")
            .ok_or_else(|| anyhow::anyhow!("No mcp_servers found in manifest"))?;

        // mcp_servers is a map: { "server_name": { command, args, ... } }
        let servers_map = mcp_servers
            .as_object()
            .ok_or_else(|| anyhow::anyhow!("mcp_servers must be an object"))?;

        for (server_name, server_value) in servers_map {
            // Inject the server name into the JSON value before deserializing
            // because McpServerConfig requires a `name` field.
            let mut server_json = server_value.clone();
            if let Some(obj) = server_json.as_object_mut() {
                if !obj.contains_key("name") {
                    obj.insert("name".to_string(), serde_json::json!(server_name));
                }
            }

            let mut server_config: crate::extensions::mcp::protocol::config::McpServerConfig =
                serde_json::from_value(server_json).with_context(|| {
                    format!("Failed to parse mcp_servers config for '{server_name}'")
                })?;

            // Set working directory to the extension directory if not specified
            if server_config.cwd.is_none() {
                server_config.cwd = Some(manifest.path.clone());
            }

            let manager = self.manager.read().await;
            let exists = manager.get_server_state(&server_config.name).await.is_ok();
            drop(manager);

            if !exists {
                let manager = self.manager.read().await;
                manager.add_server_config(server_config).await?;
                info!(server_name = %server_name, "Added MCP server config from unified manifest");
            }
        }

        Ok(())
    }

    /// Register MCP server tools with the unified registry (ADR-018b)
    ///
    /// Queries the MCP server for its tools and registers each one via
    /// `ExtensionCore::register_tool()`.  Companion hooks are auto-generated.
    pub async fn register_server_tools(
        &self,
        core: &ExtensionCore,
        server_name: &str,
        principal_id: &PrincipalId,
    ) -> Result<usize> {
        let (all_tools, server_config) = {
            let manager = self.manager.read().await;
            let tools = manager.list_all_tools().await;
            let config = manager.get_server_config(server_name).await;
            (tools, config)
        };

        let cwd = server_config.as_ref().and_then(|c| c.cwd.clone());

        let mut tools: Vec<_> = all_tools
            .into_iter()
            .filter(|(srv, _)| srv == server_name)
            .map(|(_, tool)| tool)
            .collect();

        // Phase 2: if the server is offline, fall back to the on-disk capability cache
        // so the LLM still sees the tool definitions.
        if tools.is_empty() {
            if let Some(ref cwd) = cwd {
                match crate::extensions::mcp::runtime::McpCapabilityCache::read(cwd, server_name)
                    .await
                {
                    Ok(Some(cache)) => {
                        info!(
                            server_name = %server_name,
                            tool_count = cache.tools.len(),
                            "Registered MCP tools from offline cache"
                        );
                        tools = cache.tools;
                    }
                    Ok(None) => {}
                    Err(e) => {
                        warn!(
                            server_name = %server_name,
                            error = %e,
                            "Failed to read MCP capability cache"
                        );
                    }
                }
            }
        }

        // Use the server_name as the canonical extension ID (same as manifest id)
        let ext_id = ExtensionId::new(server_name);
        let mut registered_count = 0;

        for tool in tools {
            let tool_name = format!("{}:{}:{}", MCP_TOOL_PREFIX, server_name, tool.name);

            let metadata = ToolMetadata::new(
                tool_name.clone(),
                if tool.description.is_empty() {
                    format!("MCP tool: {}", tool.name)
                } else {
                    tool.description
                },
                tool.input_schema,
                ToolSource::Mcp {
                    server: server_name.to_string(),
                },
            );

            let exec_handler = Arc::new(McpToolExecuteHandler {
                manager: self.manager.clone(),
                server_name: server_name.to_string(),
                tool_name: tool.name,
            });

            match core
                .register_tool(metadata, exec_handler, &ext_id, principal_id)
                .await
            {
                Ok(_) => {
                    debug!(tool_name = %tool_name, "Registered MCP tool");
                    registered_count += 1;
                }
                Err(e) => {
                    warn!(tool_name = %tool_name, error = %e, "Failed to register MCP tool");
                }
            }
        }

        info!(
            server_name = %server_name,
            registered = registered_count,
            "Registered MCP server tools"
        );

        Ok(registered_count)
    }

    /// Parse official MCP Registry `server.json` format (Tier 1).
    ///
    /// Normalizes the registry manifest into an `mcp_servers` compatible structure
    /// so that downstream hooks and tool registration work the same way as Tier 2.
    fn parse_server_json(
        &self,
        path: &Path,
        content: &str,
    ) -> anyhow::Result<crate::extensions::framework::ExtensionManifest> {
        use anyhow::Context;

        let registry_manifest: serde_json::Value = serde_json::from_str(content)
            .with_context(|| format!("Failed to parse server.json at {path:?}"))?;

        let name = registry_manifest
            .get("name")
            .and_then(|v| v.as_str())
            .unwrap_or("unknown")
            .to_string();
        let description = registry_manifest
            .get("description")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let version = registry_manifest
            .get("version")
            .and_then(|v| v.as_str())
            .unwrap_or("1.0.0")
            .to_string();

        let mut manifest = ExtensionManifest::new(
            &name,
            MCP_EXTENSION_TYPE,
            &name,
            &description,
            &version,
            path.parent().unwrap_or(Path::new(".")).to_path_buf(),
        );

        // Normalize registry transport config into mcp_servers format so that
        // register_tools() and the init hook can consume it the same way as
        // Tier 2 unified manifests.
        let mcp_servers = Self::registry_manifest_to_mcp_servers(&registry_manifest, path);
        if let Some(ref servers) = mcp_servers {
            manifest.set("mcp_servers", servers.clone());
        }

        manifest.set("registry_manifest", registry_manifest.clone());
        manifest.set("server_json_path", path.to_string_lossy().to_string());

        Ok(manifest)
    }

    /// Convert an MCP Registry `server.json` into the `mcp_servers` structure
    /// used by Tier 2 unified manifests.
    ///
    /// Looks at `transport` (top-level) or `packages[].transport` to build the
    /// server config map: `{ "server_name": { "command": "...", "args": [...] } }`.
    fn registry_manifest_to_mcp_servers(
        registry_manifest: &serde_json::Value,
        server_json_path: &Path,
    ) -> Option<serde_json::Value> {
        let server_name = registry_manifest
            .get("name")
            .and_then(|v| v.as_str())
            .unwrap_or("unknown");

        // Try top-level transport first
        let transport = registry_manifest.get("transport");
        // Fall back to first package's transport
        let transport = transport.or_else(|| {
            registry_manifest
                .get("packages")
                .and_then(|p| p.as_array())
                .and_then(|arr| arr.first())
                .and_then(|pkg| pkg.get("transport"))
        });

        let transport = transport?;
        let transport_type = transport
            .get("type")
            .and_then(|v| v.as_str())
            .unwrap_or("stdio");

        if transport_type != "stdio" {
            // Non-stdio transports (SSE, etc.) are not yet supported for
            // auto-start via the extension adapter.
            warn!(
                server_name = %server_name,
                transport_type = %transport_type,
                "Non-stdio transport in server.json is not yet auto-started by the MCP adapter"
            );
            return None;
        }

        let command = transport
            .get("command")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string());
        let args = transport
            .get("args")
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|v| v.as_str().map(|s| s.to_string()))
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default();

        let mut server_config = serde_json::Map::new();
        server_config.insert("name".to_string(), serde_json::json!(server_name));
        server_config.insert("transport".to_string(), serde_json::json!(transport_type));
        if let Some(cmd) = command {
            server_config.insert("command".to_string(), serde_json::json!(cmd));
        }
        if !args.is_empty() {
            server_config.insert("args".to_string(), serde_json::json!(args));
        }
        server_config.insert("auto_start".to_string(), serde_json::json!(true));

        // Set cwd to the directory containing server.json so relative paths work
        if let Some(parent) = server_json_path.parent() {
            server_config.insert(
                "cwd".to_string(),
                serde_json::json!(parent.to_string_lossy().to_string()),
            );
        }

        let mut mcp_servers = serde_json::Map::new();
        mcp_servers.insert(
            server_name.to_string(),
            serde_json::Value::Object(server_config),
        );

        Some(serde_json::Value::Object(mcp_servers))
    }

    /// Parse unified manifest.yaml with extension_type: "mcp" (Tier 2).
    fn parse_unified_yaml_manifest(
        &self,
        path: &Path,
        content: &str,
    ) -> anyhow::Result<crate::extensions::framework::ExtensionManifest> {
        use anyhow::Context;

        let yaml: serde_yaml::Value = serde_yaml::from_str(content)
            .with_context(|| format!("Failed to parse MCP YAML manifest at {path:?}"))?;

        let (id, name, version, description) =
            crate::extensions::framework::adapters::parsing::extract_extension_fields(&yaml)?;

        let mut manifest = ExtensionManifest::new(
            &id,
            MCP_EXTENSION_TYPE,
            &name,
            &description,
            &version,
            path.parent().unwrap_or(Path::new(".")).to_path_buf(),
        );

        // Store mcp_servers config if present
        if let Some(mcp_servers) = yaml.get("mcp_servers") {
            manifest.set(
                "mcp_servers",
                crate::extensions::framework::adapters::parsing::yaml_to_json(mcp_servers.clone()),
            );
        }

        // Store any additional metadata
        if let serde_yaml::Value::Mapping(map) = &yaml {
            for (k, v) in map {
                if let Some(key) = k.as_str() {
                    if ![
                        "id",
                        "name",
                        "version",
                        "description",
                        "extension_type",
                        "mcp_servers",
                    ]
                    .contains(&key)
                    {
                        manifest.set(
                            key,
                            crate::extensions::framework::adapters::parsing::yaml_to_json(
                                v.clone(),
                            ),
                        );
                    }
                }
            }
        }

        Ok(manifest)
    }

    /// Create Tool trait instances for all tools provided by an MCP server
    ///
    /// This is a **separate concern** from the Extension registry — it creates
    /// `Arc<dyn Tool>` instances for the legacy Tool trait system.  Not part of
    /// the unified registration path.
    pub async fn create_tool_instances(
        &self,
        server_name: &str,
    ) -> Result<Vec<Arc<dyn crate::tools::Tool>>> {
        let manager = self.manager.read().await;

        let all_tools = manager.list_all_tools().await;
        let server_tools: Vec<_> = all_tools
            .into_iter()
            .filter(|(srv, _)| srv == server_name)
            .map(|(_, tool)| tool)
            .collect();

        drop(manager);

        let mut tool_instances: Vec<Arc<dyn crate::tools::Tool>> = Vec::new();

        for tool in server_tools {
            let proxy = crate::extensions::mcp::runtime::tool_proxy::McpToolProxy::new(
                server_name.to_string(),
                tool,
                self.manager.clone(),
            );
            tool_instances.push(Arc::new(proxy));
        }

        info!(
            server_name = %server_name,
            tool_count = tool_instances.len(),
            "Created MCP tool instances"
        );

        Ok(tool_instances)
    }
}

impl Default for McpAdapter {
    fn default() -> Self {
        Self::with_default_manager()
    }
}

#[async_trait]
impl ExtensionTypeAdapter for McpAdapter {
    fn extension_type(&self) -> &'static str {
        MCP_EXTENSION_TYPE
    }

    fn manifest_format(&self) -> ManifestFormat {
        // ADR-024: MCP adapter supports two input paths:
        // Tier 1: server.json (MCP Registry standard)
        // Tier 2: manifest.yaml with extension_type: "mcp"
        // We use Custom detection because the adapter handles both.
        ManifestFormat::Custom {
            detector: |_path| {
                // Detection is now handled centrally by ExtensionStore's
                // three-tier hierarchy. This detector is a no-op placeholder.
                true
            },
        }
    }

    fn parse_manifest(
        &self,
        path: &Path,
        content: &str,
    ) -> anyhow::Result<crate::extensions::framework::ExtensionManifest> {
        // Dispatch to the appropriate parser based on file name
        let file_name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if file_name == "server.json" {
            self.parse_server_json(path, content)
        } else {
            self.parse_unified_yaml_manifest(path, content)
        }
    }

    fn resolve_hooks(&self, manifest: &ExtensionManifest) -> Vec<HookBinding> {
        // Only non-tool lifecycle hooks are declared here.
        // Tool-specific hooks are auto-generated by ExtensionCore::register_tool()
        // per individual tool.
        let config_path = manifest
            .get("config_path")
            .and_then(|v| v.as_str())
            .map(PathBuf::from)
            .unwrap_or_default();
        let mcp_servers = manifest.get("mcp_servers").cloned();

        vec![
            HookBinding::new(
                HookPoint::AgentInit,
                Box::new(McpServerInitFactory {
                    manager: self.manager.clone(),
                    server_name: manifest.name.clone(),
                    config_path,
                    mcp_servers,
                }),
            ),
            HookBinding::new(
                HookPoint::AgentShutdown,
                Box::new(McpServerShutdownFactory {
                    manager: self.manager.clone(),
                    server_name: manifest.name.clone(),
                }),
            ),
            HookBinding::new(
                HookPoint::PromptSystemSection {
                    section: "mcp_context".to_string(),
                    priority: MCP_HOOK_PRIORITY,
                },
                Box::new(McpContextHandlerFactory {
                    manager: self.manager.clone(),
                }),
            ),
        ]
    }

    async fn initialize(&self, manifest: &ExtensionManifest) -> Result<ExtensionState> {
        let server_name = manifest.name.clone();

        info!(server_name = %server_name, "Initializing MCP server config");

        // Ensure the server config is registered so that register_tools()
        // and the AgentInit hook can start it on demand.
        // We do NOT start the server here — starting is the responsibility
        // of the AgentInit hook (when an agent runs) or `peko ext start`.
        if let Err(e) = self.ensure_server_config_from_manifest(manifest).await {
            warn!(
                server_name = %server_name,
                error = %e,
                "Failed to ensure MCP server config during initialize"
            );
        }

        Ok(ExtensionState::Unit)
    }

    async fn shutdown(&self, _state: ExtensionState) -> Result<()> {
        Ok(())
    }

    async fn register_tools(
        &self,
        core: &crate::extensions::framework::core::ExtensionCore,
        manifest: &ExtensionManifest,
        principal_id: &PrincipalId,
    ) -> Result<usize> {
        // Try unified manifest mcp_servers (Tier 2)
        if manifest.get("mcp_servers").is_some() {
            if let Err(e) = self.ensure_server_config_from_manifest(manifest).await {
                warn!(
                    server_name = %manifest.name,
                    error = %e,
                    "Failed to ensure MCP server config from unified manifest"
                );
            }
        }

        // Determine the actual server name to use for tool registration.
        // For unified manifests with mcp_servers, use the first server key
        // instead of manifest.name (which may differ from the server config name).
        let server_name = manifest
            .get("mcp_servers")
            .and_then(|v| v.as_object())
            .and_then(|obj| obj.keys().next())
            .map(|k| k.as_str())
            .unwrap_or(&manifest.name);

        self.register_server_tools(core, server_name, principal_id)
            .await
    }
}

/// A discovered MCP server before registration
#[derive(Debug, Clone)]
pub struct DiscoveredMcpServer {
    /// Extension manifest
    pub manifest: ExtensionManifest,
    /// Path to config file
    pub config_path: PathBuf,
    /// Server directory
    pub server_dir: PathBuf,
}

// ═══════════════════════════════════════════════════════════════════════════════
// Lifecycle handlers (server-level, not tool-level)
// ═══════════════════════════════════════════════════════════════════════════════

/// Factory for MCP server init handlers
#[derive(Clone)]
struct McpServerInitFactory {
    manager: Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
    server_name: String,
    config_path: PathBuf,
    /// ADR-024: Embedded mcp_servers config from unified manifest (used when config_path is empty)
    mcp_servers: Option<serde_json::Value>,
}

impl std::fmt::Debug for McpServerInitFactory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("McpServerInitFactory")
            .field("manager", &"<McpManager>")
            .field("server_name", &self.server_name)
            .field("config_path", &self.config_path)
            .finish()
    }
}

impl HookHandlerFactory for McpServerInitFactory {
    fn create(&self, _manifest: ExtensionManifest) -> Box<dyn HookHandler> {
        Box::new(McpServerInitHandler {
            manager: self.manager.clone(),
            server_name: self.server_name.clone(),
            config_path: self.config_path.clone(),
            mcp_servers: self.mcp_servers.clone(),
        })
    }
}

/// Handler that initializes MCP server on agent init
#[derive(Clone)]
struct McpServerInitHandler {
    manager: Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
    server_name: String,
    config_path: PathBuf,
    /// ADR-024: Embedded mcp_servers config from unified manifest
    mcp_servers: Option<serde_json::Value>,
}

impl std::fmt::Debug for McpServerInitHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("McpServerInitHandler")
            .field("manager", &"<McpManager>")
            .field("server_name", &self.server_name)
            .field("config_path", &self.config_path)
            .field("has_mcp_servers", &self.mcp_servers.is_some())
            .finish()
    }
}

#[async_trait]
impl HookHandler for McpServerInitHandler {
    async fn handle(&self, _ctx: HookContext) -> HookResult {
        debug!(server_name = %self.server_name, "Initializing MCP server on agent init");

        let server_config = if self.config_path.as_os_str().is_empty() {
            // ADR-024: Load from embedded mcp_servers in unified manifest
            match &self.mcp_servers {
                Some(mcp_servers) => {
                    match Self::load_server_config_from_json(mcp_servers, &self.server_name).await {
                        Ok(config) => config,
                        Err(e) => {
                            warn!(server_name = %self.server_name, error = %e, "Failed to load MCP server config from unified manifest");
                            return HookResult::Continue(
                                crate::extensions::framework::types::HookOutput::Unit,
                            );
                        }
                    }
                }
                None => {
                    warn!(server_name = %self.server_name, "No config_path or mcp_servers available for MCP server");
                    return HookResult::Continue(
                        crate::extensions::framework::types::HookOutput::Unit,
                    );
                }
            }
        } else {
            match McpAdapter::load_server_config(&self.config_path).await {
                Ok(config) => config,
                Err(e) => {
                    warn!(server_name = %self.server_name, error = %e, "Failed to load MCP server config");
                    return HookResult::Continue(
                        crate::extensions::framework::types::HookOutput::Unit,
                    );
                }
            }
        };

        let manager = self.manager.read().await;
        let exists = manager.get_server_state(&self.server_name).await.is_ok();
        drop(manager);

        if !exists {
            let manager = self.manager.read().await;
            if let Err(e) = manager.add_server_config(server_config).await {
                warn!(server_name = %self.server_name, error = %e, "Failed to add MCP server config");
                return HookResult::Continue(crate::extensions::framework::types::HookOutput::Unit);
            }
            info!(server_name = %self.server_name, "Added MCP server config to manager");
        }

        // Do NOT auto-start the server here.  Starting the server on every
        // AgentInit hook (which fires for *any* agent, not just the one that
        // enabled this extension) causes `ext start` to fail with "Runtime
        // already exists".  The server will be started on demand by
        // `ext start` or `McpToolProxy::call_with_auto_start()`.
        let manager = self.manager.read().await;
        let _is_running = match manager.get_server_state(&self.server_name).await {
            Ok(state) if state.running => true,
            _ => false,
        };
        drop(manager);

        // Register tools with unified registry so the agent can use them.
        // Registration does not require the server to be running; tool
        // metadata was discovered when the extension was installed.
        if let Some(core) = crate::extensions::framework::core::global_core() {
            let adapter = McpAdapter::new(self.manager.clone());
            match adapter
                .register_server_tools(
                    &core,
                    &self.server_name,
                    crate::subject::PrincipalId::system(),
                )
                .await
            {
                Ok(count) => {
                    info!(server_name = %self.server_name, count = count, "Registered MCP tools with unified registry");
                }
                Err(e) => {
                    warn!(server_name = %self.server_name, error = %e, "Failed to register MCP tools");
                }
            }
        } else {
            warn!("No global ExtensionCore available for MCP tool registration");
        }

        HookResult::Continue(crate::extensions::framework::types::HookOutput::Unit)
    }

    fn hook_point(&self) -> HookPoint {
        HookPoint::AgentInit
    }

    fn priority(&self) -> i32 {
        MCP_HOOK_PRIORITY
    }

    fn name(&self) -> String {
        format!("McpServerInitHandler({})", self.server_name)
    }
}

impl McpServerInitHandler {
    /// Load server config from embedded mcp_servers JSON (ADR-024 unified manifest).
    async fn load_server_config_from_json(
        mcp_servers: &serde_json::Value,
        server_name: &str,
    ) -> Result<crate::extensions::mcp::protocol::config::McpServerConfig> {
        let servers_map = mcp_servers
            .as_object()
            .ok_or_else(|| anyhow::anyhow!("mcp_servers must be an object"))?;

        let server_value = servers_map
            .get(server_name)
            .ok_or_else(|| anyhow::anyhow!("Server '{}' not found in mcp_servers", server_name))?;

        // Inject the server name into the JSON value before deserializing
        let mut server_json = server_value.clone();
        if let Some(obj) = server_json.as_object_mut() {
            if !obj.contains_key("name") {
                obj.insert("name".to_string(), serde_json::json!(server_name));
            }
        }

        let server_config: crate::extensions::mcp::protocol::config::McpServerConfig =
            serde_json::from_value(server_json).with_context(|| {
                format!("Failed to parse mcp_servers config for '{server_name}'")
            })?;

        Ok(server_config)
    }
}

/// Factory for MCP server shutdown handlers
#[derive(Clone)]
struct McpServerShutdownFactory {
    manager: Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
    server_name: String,
}

impl std::fmt::Debug for McpServerShutdownFactory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("McpServerShutdownFactory")
            .field("manager", &"<McpManager>")
            .field("server_name", &self.server_name)
            .finish()
    }
}

impl HookHandlerFactory for McpServerShutdownFactory {
    fn create(&self, _manifest: ExtensionManifest) -> Box<dyn HookHandler> {
        Box::new(McpServerShutdownHandler {
            manager: self.manager.clone(),
            server_name: self.server_name.clone(),
        })
    }
}

/// Handler that stops MCP server on agent shutdown
#[derive(Clone)]
struct McpServerShutdownHandler {
    manager: Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
    server_name: String,
}

impl std::fmt::Debug for McpServerShutdownHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("McpServerShutdownHandler")
            .field("manager", &"<McpManager>")
            .field("server_name", &self.server_name)
            .finish()
    }
}

#[async_trait]
impl HookHandler for McpServerShutdownHandler {
    async fn handle(&self, _ctx: HookContext) -> HookResult {
        debug!(server_name = %self.server_name, "Shutting down MCP server");

        let manager = self.manager.write().await;
        match manager.stop_server(&self.server_name).await {
            Ok(()) => {
                info!(server_name = %self.server_name, "MCP server stopped");
                HookResult::Continue(crate::extensions::framework::types::HookOutput::Unit)
            }
            Err(e) => {
                warn!(server_name = %self.server_name, error = %e, "Failed to stop MCP server");
                HookResult::Continue(crate::extensions::framework::types::HookOutput::Unit)
            }
        }
    }

    fn hook_point(&self) -> HookPoint {
        HookPoint::AgentShutdown
    }

    fn priority(&self) -> i32 {
        MCP_HOOK_PRIORITY
    }

    fn name(&self) -> String {
        format!("McpServerShutdownHandler({})", self.server_name)
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Prompt context handler
// ═══════════════════════════════════════════════════════════════════════════════

/// Factory for MCP context system-prompt handlers.
#[derive(Clone)]
struct McpContextHandlerFactory {
    manager: Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
}

impl std::fmt::Debug for McpContextHandlerFactory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("McpContextHandlerFactory")
            .field("manager", &"<McpManager>")
            .finish()
    }
}

impl HookHandlerFactory for McpContextHandlerFactory {
    fn create(&self, _manifest: ExtensionManifest) -> Box<dyn HookHandler> {
        Box::new(McpContextHandler {
            manager: self.manager.clone(),
        })
    }
}

/// Handler that renders MCP server metadata (name, version, instructions,
/// capabilities) into the system prompt.
#[derive(Clone)]
struct McpContextHandler {
    manager: Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
}

impl std::fmt::Debug for McpContextHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("McpContextHandler")
            .field("manager", &"<McpManager>")
            .finish()
    }
}

#[async_trait]
impl HookHandler for McpContextHandler {
    async fn handle(&self, _ctx: HookContext) -> HookResult {
        let manager = self.manager.read().await;
        let server_states = manager.list_server_prompt_context().await;
        drop(manager);

        if server_states.is_empty() {
            return HookResult::Continue(HookOutput::Text(String::new()));
        }

        let mut lines = vec![
            "## MCP Servers".to_string(),
            "The following Model Context Protocol (MCP) servers are configured. \
             When a server is offline, its tools are still listed but will be \
             started automatically if you invoke one."
                .to_string(),
            String::new(),
        ];

        for state in server_states {
            let status_label = if state.running {
                if state.healthy {
                    "running"
                } else {
                    "running (unhealthy)"
                }
            } else {
                "offline"
            };

            let info = state
                .server_info
                .as_ref()
                .map(|s| format!(" — {s}"))
                .unwrap_or_default();
            lines.push(format!("- **{}** ({}){}", state.name, status_label, info));

            if let Some(instructions) = state.instructions {
                lines.push(format!("  - Instructions: {}", instructions));
            }

            if !state.tools.is_empty() {
                let tool_names: Vec<String> = state.tools.iter().map(|t| t.name.clone()).collect();
                lines.push(format!("  - Tools: {}", tool_names.join(", ")));
            }

            if !state.resources.is_empty() {
                let resource_names: Vec<String> = state
                    .resources
                    .iter()
                    .map(|r| format!("{} ({})", r.uri, r.name))
                    .collect();
                lines.push(format!("  - Resources: {}", resource_names.join(", ")));
            }

            if !state.prompts.is_empty() {
                let prompt_names: Vec<String> = state
                    .prompts
                    .iter()
                    .map(|p| {
                        let args = p.arguments.as_ref().map_or(String::new(), |args| {
                            let names: Vec<String> = args.iter().map(|a| a.name.clone()).collect();
                            if names.is_empty() {
                                String::new()
                            } else {
                                format!(" ({})", names.join(", "))
                            }
                        });
                        format!("{}{}", p.name, args)
                    })
                    .collect();
                lines.push(format!("  - Prompts: {}", prompt_names.join(", ")));
            }
        }

        HookResult::Continue(HookOutput::Text(lines.join("\n")))
    }

    fn hook_point(&self) -> HookPoint {
        HookPoint::PromptSystemSection {
            section: "mcp_context".to_string(),
            priority: MCP_HOOK_PRIORITY,
        }
    }

    fn priority(&self) -> i32 {
        MCP_HOOK_PRIORITY
    }

    fn name(&self) -> String {
        "McpContextHandler".to_string()
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Tool execution handler (the only adapter-specific handler for tools)
// ═══════════════════════════════════════════════════════════════════════════════

/// Handler that executes MCP tools via the MCP manager.
#[derive(Clone)]
struct McpToolExecuteHandler {
    manager: Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
    server_name: String,
    tool_name: String,
}

impl std::fmt::Debug for McpToolExecuteHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("McpToolExecuteHandler")
            .field("manager", &"<McpManager>")
            .field("server_name", &self.server_name)
            .field("tool_name", &self.tool_name)
            .finish()
    }
}

#[async_trait]
impl HookHandler for McpToolExecuteHandler {
    async fn handle(&self, ctx: HookContext) -> HookResult {
        let (called_tool_name, _params) = match ctx.as_tool_call() {
            Some((tool_name, params, _)) => {
                let expected_prefix = format!("{}:{}", MCP_TOOL_PREFIX, self.server_name);
                if !tool_name.starts_with(&expected_prefix) {
                    return HookResult::PassThrough;
                }
                (tool_name.to_string(), params.clone())
            }
            None => return HookResult::PassThrough,
        };

        let expected_full_name = format!(
            "{}:{}:{}",
            MCP_TOOL_PREFIX, self.server_name, self.tool_name
        );
        if called_tool_name != expected_full_name {
            return HookResult::PassThrough;
        }

        debug!(
            server_name = %self.server_name,
            tool_name = %self.tool_name,
            "Executing MCP tool via Extension Framework"
        );

        let server_config = {
            let manager = self.manager.read().await;
            manager.get_server_config(&self.server_name).await
        };

        let reserved_params = server_config
            .as_ref()
            .map(|c| c.reserved_parameters.clone())
            .unwrap_or_default();

        let manager = self.manager.clone();
        let server_name = self.server_name.clone();
        let actual_tool = self.tool_name.clone();

        // F19: capture principal_id from the framework-injected
        // `ToolRuntimeContext` so tool-call-driven auto-start can hand
        // the principal's quota meter to the MCP server's sampling
        // handler. None means the call originated from a non-principal
        // scope (CLI, tests, internal auto-start) — the server gets an
        // unlimited meter.
        let calling_principal_id: Option<String> = ctx
            .get_state::<crate::extensions::framework::types::ToolRuntimeContext>("tool_context")
            .and_then(|tc| tc.principal_id.clone());

        let exec_config = peko_extension_host::ToolExecConfig::new(
            reserved_params,
            serde_json::json!({"type": "object"}),
        );

        ctx.services.async_router()
            .execute_from_hook(
                &ctx,
                &called_tool_name,
                &exec_config,
                None::<peko_extension_host::PreprocessorFn>,
                Box::new(move |p| {
                    let manager = manager.clone();
                    let server = server_name.clone();
                    let tool = actual_tool.clone();
                    let principal_id = calling_principal_id.clone();
                    Box::pin(async move {
                        // Phase 2: on-demand server start. If the MCP server is not
                        // running when the tool is invoked, attempt to start it once.
                        let needs_start = {
                            let mgr = manager.read().await;
                            match mgr.get_server_state(&server).await {
                                Ok(state) => !state.running,
                                Err(_) => true,
                            }
                        };

                        if needs_start {
                            info!(server_name = %server, "MCP server not running; starting on demand");
                            let mgr = manager.write().await;
                            // F19: tool-call-driven auto-start. The
                            // server's sampling handler will charge
                            // the calling principal's meter.
                            match mgr
                                .start_server(&server, principal_id.as_deref())
                                .await
                            {
                                Ok(()) => {
                                    info!(server_name = %server, "MCP server started on demand");
                                }
                                Err(crate::extensions::mcp::protocol::manager::ManagerError::ServerAlreadyRunning(_)) => {
                                    debug!(server_name = %server, "MCP server already running");
                                }
                                Err(e) => {
                                    return Err(anyhow::anyhow!(
                                        "MCP server '{}' could not be started for tool '{}': {}",
                                        server, tool, e
                                    ));
                                }
                            }
                        }

                        let mgr = manager.read().await;
                        let mcp_result = mgr.call_tool(&server, &tool, p).await?;
                        let json_result = serde_json::json!({
                            "success": !mcp_result.is_error,
                            "contents": mcp_result.content.iter().map(|c| match c {
                                crate::extensions::mcp::protocol::types::ToolResultContent::Text(t) => serde_json::json!({
                                    "type": "text",
                                    "text": t.text
                                }),
                                crate::extensions::mcp::protocol::types::ToolResultContent::Image(i) => serde_json::json!({
                                    "type": "image",
                                    "data": i.data,
                                    "mime_type": i.mime_type
                                }),
                                crate::extensions::mcp::protocol::types::ToolResultContent::Resource(r) => serde_json::json!({
                                    "type": "resource",
                                    "resource": r.resource
                                }),
                            }).collect::<Vec<_>>(),
                        });
                        Ok(json_result)
                    }) as futures::future::BoxFuture<'static, anyhow::Result<serde_json::Value>>
                }) as peko_extension_host::ExecFn,
            )
            .await
    }

    fn hook_point(&self) -> HookPoint {
        HookPoint::ToolExecute {
            tool_name: format!(
                "{}:{}:{}",
                MCP_TOOL_PREFIX, self.server_name, self.tool_name
            ),
        }
    }

    fn priority(&self) -> i32 {
        MCP_HOOK_PRIORITY
    }

    fn name(&self) -> String {
        format!("McpToolExecuteHandler({})", self.server_name)
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Helper functions
// ═══════════════════════════════════════════════════════════════════════════════

/// Load MCP servers from directory using the adapter
pub async fn load_servers_from_directory(
    path: &Path,
    manager: Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
) -> Vec<DiscoveredMcpServer> {
    let adapter = McpAdapter::new(manager);
    adapter.discover_servers(path).await
}

/// Load and register MCP servers with an ExtensionCore
pub async fn load_and_register_servers(
    core: &crate::extensions::framework::ExtensionCore,
    servers_dir: impl AsRef<Path>,
    manager: Arc<RwLock<crate::extensions::mcp::protocol::manager::McpManager>>,
) -> Result<usize> {
    let adapter = McpAdapter::new(manager.clone());
    let servers = adapter.discover_servers(servers_dir.as_ref()).await;
    let mut total_tools = 0;
    for server in servers {
        // Register lifecycle hooks (init/shutdown)
        let extension_id = ExtensionId::new(&server.manifest.id.0);
        let bindings = adapter.resolve_hooks(&server.manifest);
        for binding in bindings {
            let handler = binding.handler_factory.create(server.manifest.clone());
            let handler_arc: Arc<dyn HookHandler> = handler.into();
            core.register_hook(binding.point, handler_arc, &extension_id)
                .await?;
        }
        // Register tools via unified registry
        if let Some(config_path) = server.manifest.get("config_path").and_then(|v| v.as_str()) {
            let _ = adapter.ensure_server_config(config_path).await;
        }
        match adapter
            .register_server_tools(
                core,
                &server.manifest.name,
                crate::subject::PrincipalId::system(),
            )
            .await
        {
            Ok(n) => total_tools += n,
            Err(e) => {
                warn!(server = %server.manifest.name, error = %e, "Failed to register MCP tools")
            }
        }
    }
    Ok(total_tools)
}

// ═══════════════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn create_test_server_config(dir: &Path, name: &str) -> PathBuf {
        let server_dir = dir.join(name);
        std::fs::create_dir_all(&server_dir).unwrap();
        let server_json_path = server_dir.join("server.json");
        let manifest = serde_json::json!({
            "name": name,
            "version": "1.0.0",
            "description": format!("MCP server: {name}"),
            "transport": {
                "type": "stdio",
                "command": "echo",
                "args": ["test"]
            }
        });
        std::fs::write(&server_json_path, manifest.to_string()).unwrap();
        server_json_path
    }

    #[test]
    fn test_mcp_adapter_manifest_format() {
        let adapter = McpAdapter::with_default_manager();
        let format = adapter.manifest_format();

        assert!(matches!(format, ManifestFormat::Custom { .. }));
    }

    #[tokio::test]
    async fn test_discover_servers() {
        let temp = TempDir::new().unwrap();

        create_test_server_config(temp.path(), "server1");
        create_test_server_config(temp.path(), "server2");

        let adapter = McpAdapter::with_default_manager();
        let servers = adapter.discover_servers(temp.path()).await;

        assert_eq!(servers.len(), 2);
        assert!(servers.iter().any(|s| s.manifest.name == "server1"));
        assert!(servers.iter().any(|s| s.manifest.name == "server2"));
    }

    #[tokio::test]
    async fn test_parse_server_json() {
        let temp = TempDir::new().unwrap();
        let config_path = create_test_server_config(temp.path(), "filesystem");

        let adapter = McpAdapter::with_default_manager();
        let content = std::fs::read_to_string(&config_path).unwrap();
        let manifest = adapter.parse_manifest(&config_path, &content).unwrap();

        assert_eq!(manifest.name, "filesystem");
        assert_eq!(manifest.extension_type, "mcp");
    }

    #[tokio::test]
    async fn test_mcp_tool_execute_handler() {
        let manager = Arc::new(RwLock::new(
            crate::extensions::mcp::protocol::manager::McpManager::new(
                crate::extensions::mcp::protocol::config::McpConfig::default(),
            ),
        ));

        let handler = McpToolExecuteHandler {
            manager,
            server_name: "test".to_string(),
            tool_name: "echo".to_string(),
        };

        assert_eq!(handler.server_name, "test");
        assert_eq!(handler.tool_name, "echo");
    }
}
